ALTER TABLE ROAD_STATION_SENSOR
RENAME COLUMN DESCRIPTION TO DESCRIPTION_FI;

ALTER TABLE ROAD_STATION_SENSOR
  ADD PRESENTATION_NAME_FI            CHARACTER VARYING(200),
  ADD PRESENTATION_NAME_SV            CHARACTER VARYING(200),
  ADD PRESENTATION_NAME_EN            CHARACTER VARYING(200),
  ADD DESCRIPTION_SV                  CHARACTER VARYING(200),
  ADD DESCRIPTION_EN                  CHARACTER VARYING(200),
  ADD VEHICLE_CLASS                   CHARACTER VARYING(200),
  ADD LANE                            NUMERIC(10),
  ADD DIRECTION                       NUMERIC(1),
  ADD IS_PUBLIC                       BOOLEAN,
  ADD PUBLISHABLE                     BOOLEAN;

UPDATE ROAD_STATION_SENSOR
SET IS_PUBLIC = TRUE,
    PUBLISHABLE = TRUE;

ALTER TABLE ROAD_STATION_SENSOR
  ALTER COLUMN IS_PUBLIC SET NOT NULL;

ALTER TABLE ROAD_STATION_SENSOR
  ALTER COLUMN PUBLISHABLE SET NOT NULL;

ALTER TABLE ROAD_STATION
  ADD PURPOSE CHARACTER VARYING(4000);
