ALTER TABLE ROAD_STATION_SENSOR
ADD PRESENTATION_NAME_FI            CHARACTER VARYING(200),
ADD PRESENTATION_NAME_SV            CHARACTER VARYING(200),
ADD PRESENTATION_NAME_EN            CHARACTER VARYING(200),
ADD DESCRIPTION_SV                  CHARACTER VARYING(200),
ADD DESCRIPTION_EN                  CHARACTER VARYING(200),
ADD VEHICLE_CLASS                   CHARACTER VARYING(200),
ADD IS_PUBLIC                       BOOLEAN NOT NULL DEFAULT FALSE,
ADD LANE                            NUMERIC(10),
ADD DIRECTION                       NUMERIC(1);

UPDATE ROAD_STATION_SENSOR
SET IS_PUBLIC = TRUE;



