CREATE SEQUENCE SEQ_WORK_MACHINE;
CREATE SEQUENCE SEQ_WORK_MACHINE_OBSERVATION;

CREATE TABLE WORK_MACHINE (
  ID                BIGINT PRIMARY KEY,
  HARJA_ID          BIGINT NOT NULL,
  HARJA_URAKKA_ID   BIGINT NOT NULL,
  TYPE              TEXT   NOT NULL
);

CREATE TABLE WORK_MACHINE_OBSERVATION (
  ID                      BIGINT PRIMARY KEY,
  WORK_MACHINE_ID         BIGINT REFERENCES WORK_MACHINE(id) NOT NULL,
  TYPE                    TEXT NOT NULL,
  DIRECTION               INTEGER,
  LAST_OBSERVATION_TIME   TIMESTAMP(0) WITH TIME ZONE,
  UPDATED                 TIMESTAMP(0) WITH TIME ZONE
);

CREATE TABLE WORK_MACHINE_OBSERVATION_COORDINATE (
  WORK_MACHINE_OBSERVATION_ID   BIGINT REFERENCES WORK_MACHINE_OBSERVATION(id) NOT NULL,
  ORDER_NUMBER                  INTEGER,
  LONGITUDE                     NUMERIC(10,7),
  LATITUDE                      NUMERIC(10,7),
  OBSERVATION_TIME              TIMESTAMP(0) WITH TIME ZONE,
  PRIMARY KEY(WORK_MACHINE_OBSERVATION_ID, ORDER_NUMBER),
  CONSTRAINT WORK_MACHINE_OBSERVATION_COORDINATE_UNIQUE_FK_I UNIQUE(WORK_MACHINE_OBSERVATION_ID,ORDER_NUMBER)
);

CREATE TABLE WORK_MACHINE_TASK (
  WORK_MACHINE_COORDINATE_OBSERVATION_ID   BIGINT NOT NULL,
  WORK_MACHINE_COORDINATE_ORDER_NUMBER     BIGINT NOT NULL,
  TASK                                     TEXT NOT NULL,
  PRIMARY KEY(WORK_MACHINE_COORDINATE_OBSERVATION_ID, WORK_MACHINE_COORDINATE_ORDER_NUMBER, TASK),
  FOREIGN KEY (WORK_MACHINE_COORDINATE_OBSERVATION_ID, WORK_MACHINE_COORDINATE_ORDER_NUMBER)
    REFERENCES WORK_MACHINE_OBSERVATION_COORDINATE (WORK_MACHINE_OBSERVATION_ID, ORDER_NUMBER),
  CONSTRAINT WORK_MACHINE_TASK_UNIQUE_FK_I UNIQUE(WORK_MACHINE_COORDINATE_OBSERVATION_ID, WORK_MACHINE_COORDINATE_ORDER_NUMBER, TASK)
);

CREATE INDEX WORK_MACHINE_OBSERVATION_FK_I ON WORK_MACHINE_OBSERVATION
USING BTREE (WORK_MACHINE_ID, UPDATED );