-- C01502
ALTER TABLE CAMERA_PRESET_HISTORY
    ADD COLUMN CAMERA_ID CHARACTER VARYING(6);

UPDATE CAMERA_PRESET_HISTORY
SET CAMERA_ID = SUBSTRING(preset_id, 1, 6);

ALTER TABLE CAMERA_PRESET_HISTORY ALTER COLUMN CAMERA_ID SET NOT NULL;

CREATE INDEX CAMERA_PRESET_HISTORY_LAST_MODIFIED_PUBLISHABLE_CAMERA_I
    ON CAMERA_PRESET_HISTORY
        USING BTREE (last_modified ASC, camera_id ASC) where publishable = TRUE;
COMMENT ON INDEX CAMERA_PRESET_HISTORY_LAST_MODIFIED_I is 'Used when searching history for camera';