CREATE SEQUENCE SEQ_WORK_MACHINE_TRACKING
  INCREMENT BY 1
  MAXVALUE 9223372036854775807
  MINVALUE 1
  NO CYCLE;


CREATE TABLE WORK_MACHINE_TRACKING
(
  id NUMBER(10, 0) NOT NULL,
  record JSONB,
  CONSTRAINT WORK_MACHINE_TRACKING_PKEY PRIMARY KEY (id)
)