CREATE SEQUENCE SEQ_MAINTENANCE_REALIZATION;

CREATE TABLE IF NOT EXISTS MAINTENANCE_REALIZATION
(
    id                      BIGINT NOT NULL PRIMARY KEY,
    job_id                  BIGINT NOT NULL, -- harja urakka
    sending_system          TEXT NOT NULL,
    sending_time            TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    message_id              INTEGER NOT NULL,
    line_string             GEOMETRY(LINESTRINGZ, 4326) NOT NULL, -- 4326 = WGS84
    realization_data_id     BIGINT NOT NULL
        REFERENCES MAINTENANCE_REALIZATION_DATA(id),
    created                 TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE MAINTENANCE_REALIZATION is 'JOB_ID is HARJAs urakka id';

CREATE INDEX MAINTENANCE_REALIZATION_DATA_FK ON MAINTENANCE_REALIZATION
USING BTREE (realization_data_id ASC);

CREATE TABLE MAINTENANCE_REALIZATION_POINT (
    realization_id              BIGINT REFERENCES MAINTENANCE_REALIZATION(id) NOT NULL,
    order_number                INTEGER NOT NULL,
    time                        TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    PRIMARY KEY(realization_id, order_number)
);

CREATE TABLE MAINTENANCE_REALIZATION_TASK (
    realization_id            BIGINT NOT NULL
        REFERENCES MAINTENANCE_REALIZATION(id) ON DELETE CASCADE,
    task_id                   BIGINT NOT NULL
        REFERENCES MAINTENANCE_TASK(id) ON DELETE CASCADE,
    PRIMARY KEY(realization_id, task_id)
);

CREATE INDEX MAINTENANCE_REALIZATION_TASK_TASK_ID_FK_I ON MAINTENANCE_REALIZATION_TASK USING BTREE (task_id);

