CREATE SEQUENCE SEQ_WORK_MACHINE_REALIZATION;

CREATE TABLE IF NOT EXISTS WORK_MACHINE_REALIZATION
(
    id      BIGINT NOT NULL PRIMARY KEY,
    json    TEXT NOT NULL,
    status  varchar(20) NOT NULL,
    created timestamp(0) with time zone not null default now(),
    modified timestamp(0) with time zone not null default now()
);

ALTER TABLE WORK_MACHINE_REALIZATION
    ADD CONSTRAINT WORK_MACHINE_REALIZATION_STATUS_CHECK CHECK (status IN ('UNHANDLED', 'HANDLED', 'ERROR'));

CREATE INDEX WORK_MACHINE_TRACKING_HANDLING_I
    ON WORK_MACHINE_REALIZATION
        USING BTREE (status, id ASC) where status = 'UNHANDLED';

CREATE OR REPLACE FUNCTION update_modified_column()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.modified = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER WORK_MACHINE_REALIZATION_MODIFIED BEFORE UPDATE ON WORK_MACHINE_REALIZATION FOR EACH ROW EXECUTE PROCEDURE update_modified_column();