CREATE SEQUENCE SEQ_MAINTENANCE_TASK_OPERATION;
CREATE TABLE IF NOT EXISTS MAINTENANCE_TASK_OPERATION (
    ID    BIGINT PRIMARY KEY,
    FI    TEXT NOT NULL,
    SV    TEXT,
    EN    TEXT
);

CREATE SEQUENCE SEQ_MAINTENANCE_TASK_CATEGORY;
CREATE TABLE IF NOT EXISTS MAINTENANCE_TASK_CATEGORY (
    ID    BIGINT PRIMARY KEY,
    FI    TEXT   NOT NULL,
    SV    TEXT,
    EN    TEXT
);

CREATE TABLE IF NOT EXISTS MAINTENANCE_TASK (
    ID              BIGINT PRIMARY KEY,
    FI              TEXT NOT NULL,
    SV              TEXT,
    EN              TEXT,
    OPERATION_ID    BIGINT references MAINTENANCE_TASK_OPERATION(ID) ON DELETE CASCADE NOT NULL,
    CATEGORY_ID     BIGINT references MAINTENANCE_TASK_CATEGORY(ID) ON DELETE CASCADE NOT NULL
);
COMMENT ON TABLE MAINTENANCE_TASK is 'ID is HARJA tehtava id';


CREATE INDEX MAINTENANCE_TASK_CATEGORY_ID_FKEY_I ON MAINTENANCE_TASK USING BTREE (category_id);
CREATE INDEX MAINTENANCE_TASK_OPERATION_ID_FKEY_I ON MAINTENANCE_TASK USING BTREE (operation_id);

-- Populate categories
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Kevyen liikenteen järjestely T');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Liikenneturvallisuustoimenpiteet');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Liikenneympäristön hoito');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Liikenneympäristön parantaminen');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'MHU ja HJU hoidon johto');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'MHU Ylläpito');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Päällyste');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Päällystetyn tien tierakenne');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Projektiin liittyvä suunnittelu-, teettämis-, ja valvontapalvelu');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Soratien hoito');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Soratien rakenne');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Talvihoito');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Tiemerkintä');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Tiesilta');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Tieväylä');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Varuste ja laite');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO MAINTENANCE_TASK_CATEGORY (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_CATEGORY'), 'Vesiliikenteen käyttöpalvelut');

-- Populate operations
INSERT INTO MAINTENANCE_TASK_OPERATION (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_OPERATION'), 'Laaja toimenpide');
INSERT INTO MAINTENANCE_TASK_OPERATION (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_OPERATION'), 'Liikenneympäristön hoito laaja TPI');
INSERT INTO MAINTENANCE_TASK_OPERATION (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_OPERATION'), 'Liikenneympäristön parantaminen laaja TPI');
INSERT INTO MAINTENANCE_TASK_OPERATION (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_OPERATION'), 'MHU ja HJU Hoidon johto');
INSERT INTO MAINTENANCE_TASK_OPERATION (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_OPERATION'), 'Päällystepaikkaukset laaja TPI');
INSERT INTO MAINTENANCE_TASK_OPERATION (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_OPERATION'), 'Päällystetyn tien rakenne laaja TPI');
INSERT INTO MAINTENANCE_TASK_OPERATION (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_OPERATION'), 'Soratien hoito laaja TPI');
INSERT INTO MAINTENANCE_TASK_OPERATION (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_OPERATION'), 'Soratien rakenne laaja TPI');
INSERT INTO MAINTENANCE_TASK_OPERATION (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_OPERATION'), 'Talvihoito laaja TPI');
INSERT INTO MAINTENANCE_TASK_OPERATION (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_OPERATION'), 'Tiesilta laaja TPI');
INSERT INTO MAINTENANCE_TASK_OPERATION (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_OPERATION'), 'Tieväylä laaja TPI');
INSERT INTO MAINTENANCE_TASK_OPERATION (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_OPERATION'), 'Valaistuksen korjaus');
INSERT INTO MAINTENANCE_TASK_OPERATION (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_OPERATION'), 'Varuste ja laite korjaus laaja TPI');
INSERT INTO MAINTENANCE_TASK_OPERATION (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_OPERATION'), 'Varuste ja laite laaja TPI');
INSERT INTO MAINTENANCE_TASK_OPERATION (ID, FI) VALUES (nextval('SEQ_MAINTENANCE_TASK_OPERATION'), 'Vesiliikenteen käyttöpalvelut laaja TPI');


INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12911, 'Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Laaja toimenpide'), (select c.id from maintenance_task_category c where c.fi = 'Kevyen liikenteen järjestely T'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12913, 'Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Laaja toimenpide'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneturvallisuustoimenpiteet'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12811, 'Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1439, 'Graffitien poisto', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1357, 'Harjaus', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6883, 'Harjaus ja roskien poisto', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1438, 'Huonokuntoisten viittojen ja opastetaulujen uusiminen', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1437, 'Hylättyjen ajoneuvojen siirto', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1436, 'Katupölynsidonta', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1435, 'Kolmannen osapuolen vahinkojen korjaukset', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6956, 'Kolmansien osapuolien vahinkojen korjaukset', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1356, 'Koneellinen niitto', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1355, 'Koneellinen vesakonraivaus', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6893, 'Liikennemerkkien, opasteiden ja liikenteenohjauslaitteiden hoito sekä reunapaalujen kp', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (5677, 'Liikenneympäristön hoito - Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1354, 'L- ja p-alueiden puhdistus', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7038, 'Luvattomien mainosten poistaminen', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1505, 'Maastopalvelu', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7062, 'Maastopartio (auto + 2 ram)', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7089, 'Meluesteiden pesu', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6926, 'Metsähakkuu tienvarresta', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1432, 'Metsän harvennus', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (2866, 'Muu liikenneympäristön hoito', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6882, 'Muut viheralueiden hoitoon liittyvät työt', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (2867, 'Nurmetuksen hoito / niitto', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1431, 'Opastinviitan tai -taulun uusiminen ja lisääminen -ajoradan yläpuoliset opasteet', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6924, 'Opastustaulujen ja opastusviittojen uusiminen portaaliin', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6989, 'Opastustaulujen ja opastusviittojen uusiminen -portaalissa olevan viitan/opastetaulun uusiminen', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1429, 'Opastustaulujen ja opastusviittojen uusiminen -porttaalissa olevan viitan/opastetaulun uusiminen', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1428, 'Opastustaulujen ja opastusviittojen uusiminen -vanhan viitan/opastetaulun uusiminen', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1427, 'Opastustaulujen ja opastusviittojen uusiminen -vanhan viitan/opastetaulun uusiminen/uuden asentaminen tukirakenteineen', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1426, 'Pensaiden poisto', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1425, 'Pensaiden täydennysistutus', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6898, 'Porttaalien tarkastus ja huolto', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1424, 'Porttaalien vuositarkastus', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (2865, 'Puiden ja pensaiden hoito', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1423, 'Puun poisto raivausjätteineen (taajaman ulkopuolella)', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1422, 'Puun poisto raivausjätteineen (taajamassa)', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6992, 'Pysäkkikatosten hoito, tavanomaiset sis. talvi- ja kesähoidon sekä rakenteiden huoltamisen (uudet)', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6991, 'Pysäkkikatosten hoito, vilkkaat sis. talvi- ja kesähoidon sekä rakenteiden huoltamisen (uudet)', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7044, 'Pysäkkikatosten oikaisu', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7043, 'Pysäkkikatosten tarkastus, kunnostus ja huoltomaalaus', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6869, 'Päällystettyjen teiden palteen poisto', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1414, 'Päällystettyjen teiden palteiden poisto', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1411, 'Päällystettyjen teiden sorapientareen kunnossapito', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7067, 'Päällystettyjen teiden sorapientareen täyttö', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6881, 'Risteysalueiden näkemäraivaus', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6999, 'Roskien poisto ja kevätsiivoukset L- ja P-alueilta', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6997, 'Roskien poisto ja kevätsiivoukset muut tiet', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6998, 'Roskien poisto ja kevätsiivoukset taajamat, kevarit ja päätiet', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6899, 'Rumpujen aukaisu ja muut rumpujen hoitoon liittyvät työt', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1407, 'Rumpujen korjaus ja uusiminen', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1406, 'Rumpujen korjaus ja uusiminen  600 - 1000 mm', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1405, 'Rumpujen korjaus ja uusiminen <= 600 mm', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6943, 'Rumpujen korjaus ja uusiminen  Ø> 600 - 1000 mm', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6945, 'Rumpujen korjaus ja uusiminen  ≤Ø 600 mm', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1404, 'Rumpujen korjaus/uusiminen/rakentaminen', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1408, 'Rumpujen korj./uusiminen/rakentaminen ilman siirtymäkiilaa', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1403, 'Runkopuiden poisto', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1402, 'Runkopuiden täydennysistutus', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (2868, 'Siltojen ja laitureiden puhdistus', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1398, 'Siltojen vuositarkastus', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1396, 'Sisääntuloteiden siisteyden varmistaminen', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1395, 'Tunnelin laitteiden toimivuuden testaukset', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1394, 'Tunnelin paikalliskeskuksen hoito', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1393, 'Tunnelin pesu ja muu puhtaanapito', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1392, 'Tunnelin pumppaamon poistoputken pään laskuojan huolto', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6900, 'Tunnelin vikakorjaukset, 2 rakennusammattimies', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6953, 'Vakiokokoisten liikennemerkkien uusiminen ja lisääminen merkki tukirakenteineen (60 mm varsi)', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6903, 'Vakiokokoisten liikennemerkkien uusiminen ja lisääminen merkki tukirakenteineen (90 mm varsi)', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6902, 'Vakiokokoisten liikennemerkkien uusiminen, merkin vaihto tukirakenteineen', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7000, 'Valvontakameratolppien puhdistus/tarkistus keväisin', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1391, 'Vesakonraivaus/ha', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12826, 'Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön parantaminen laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön parantaminen'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6932, 'Liikennesaarekkeen kunnostus', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön parantaminen laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön parantaminen'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (5692, 'Liikenneympäristön parantaminen - Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Liikenneympäristön parantaminen laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Liikenneympäristön parantaminen'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7055, 'Sorapintaisten jk+pp -teiden kesähoito', (select o.id from maintenance_task_operation o where o.fi = 'MHU ja HJU Hoidon johto'), (select c.id from maintenance_task_category c where c.fi = 'MHU ja HJU hoidon johto'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12825, 'Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Laaja toimenpide'), (select c.id from maintenance_task_category c where c.fi = 'MHU Ylläpito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (5691, 'Projektiin liittyvä suunnittelu-, teettämis-, ja valvontapalvelu - Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Laaja toimenpide'), (select c.id from maintenance_task_category c where c.fi = 'MHU Ylläpito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12809, 'Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Laaja toimenpide'), (select c.id from maintenance_task_category c where c.fi = 'Projektiin liittyvä suunnittelu-, teettämis-, ja valvontapalvelu'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (5675, 'Projektiin liittyvä suunnittelu-, teettämis-, ja valvontapalvelu - Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Laaja toimenpide'), (select c.id from maintenance_task_category c where c.fi = 'Projektiin liittyvä suunnittelu-, teettämis-, ja valvontapalvelu'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14524, 'Kuumapäällyste, ab käsityönä', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14525, 'Kuumapäällyste, valuasfaltti', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14526, 'Päällysteen korjaus mastiksilla siltakohteiden heitoissa', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14527, 'Päällysteiden paikkaus - Konetiivistetty massasaumaus 20 cm leveä', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14528, 'Päällysteiden paikkaus - konetiivistetty -valuasfaltti', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14529, 'Päällysteiden paikkaus - kuumapäällyste', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14542, 'Päällysteiden paikkaus, kylmäpäällyste', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14530, 'Päällysteiden paikkaus - massasaumaus', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14541, 'Päällysteiden paikkaus -saumojen juottaminen mastiksilla', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14531, 'Päällysteiden paikkaus - valuasfaltti', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14544, 'Reunapalkin ja päällysteen välisen sauman tiivistäminen', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14543, 'Reunapalkin ja päällysteen väl. sauman tiivistäminen', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14545, 'Reunapalkin liikuntasauman tiivistäminen', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14546, 'Sillan kannen päällysteen päätysauman korjaukset', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14547, 'Sillan päällysteen halkeaman avarrussaumaus', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14548, 'Sillan päällysteen halkeaman sulkeminen', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (14549, 'SIP paikkaus (kesto+kylmä)', (select o.id from maintenance_task_operation o where o.fi = 'Päällystepaikkaukset laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällyste'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6901, 'Avo-ojitus / päällystetyt muut tiet ja soratiet', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7054, 'Avo-ojitus / päällystetyt tiet', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7090, 'Avo-ojitus/päällystetyt tiet (kaapeli kaivualueella)', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6918, 'Avo-ojitus / päällystetyt vt-, kt- ja seututiet', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12832, 'Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7009, 'Laskuojat/päällystetyt tiet', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7056, 'Päällystettyjen teiden pölynsidonta', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6916, 'Päällystettyjen teiden rumpujen ohjelmoitu uusiminen 1000 mm', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6915, 'Päällystettyjen teiden rumpujen ohjelmoitu uusiminen 1200 mm', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6917, 'Päällystettyjen teiden rumpujen ohjelmoitu uusiminen 800 mm', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6919, 'Päällystetyn tien avo-ojitus', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7039, 'Päällystetyn tien rumpujen korjaus ja uusiminen Ø> 1000 <= 1200 mm', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6905, 'Päällystetyn tien rumpujen korjaus ja uusiminen  Ø> 600  <= 800 mm', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6906, 'Päällystetyn tien rumpujen korjaus ja uusiminen Ø <= 600 mm', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6904, 'Päällystetyn tien rumpujen korjaus ja uusiminen  Ø> 800 <= 1000 mm', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (5698, 'Päällystetyn tien tierakenne - Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Päällystetyn tien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Päällystetyn tien tierakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (5676, 'Alueurakan soratien hoito - Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Soratien hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6925, 'Liikenteen varmistaminen kelirikkokohteessa', (select o.id from maintenance_task_operation o where o.fi = 'Soratien hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12810, 'Muut sorateiden hoitoon liittyvät tehtävät', (select o.id from maintenance_task_operation o where o.fi = 'Soratien hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7008, 'Oja- ja luiskameteriaalin käyttö kulutuskerrokseeen', (select o.id from maintenance_task_operation o where o.fi = 'Soratien hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7012, 'Rumpujen ohjelmoitu uusiminen', (select o.id from maintenance_task_operation o where o.fi = 'Soratien hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1359, 'Sorastus km', (select o.id from maintenance_task_operation o where o.fi = 'Soratien hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1389, 'Sorateiden kaventaminen', (select o.id from maintenance_task_operation o where o.fi = 'Soratien hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1362, 'Sorateiden muokkaushöyläys', (select o.id from maintenance_task_operation o where o.fi = 'Soratien hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (2869, 'Sorateiden pinnan hoito', (select o.id from maintenance_task_operation o where o.fi = 'Soratien hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1361, 'Sorateiden pölynsidonta', (select o.id from maintenance_task_operation o where o.fi = 'Soratien hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1360, 'Sorateiden tasaus', (select o.id from maintenance_task_operation o where o.fi = 'Soratien hoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien hoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12829, 'Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7048, 'Kallion leikkaus ja maakivien poisto', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7050, 'Laskuojat/soratiet', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6921, 'Maakivien poisto', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7049, 'Ojitusmaiden ajo läjitykseen', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7047, 'Päällysteen purku/ muuttaminen soratieksi', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6965, 'Rummun uusiminen >600 ilman kiiloja (max 1000) sorateillä', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6964, 'Rummun uusiminen >600 kiiloineen (max 1000) sorateillä', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6952, 'Rumpujen rakentaminen sorateille siirtymäkiilalla', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7063, 'Sorapintaisten jk+pp -teiden kesähoito', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6950, 'Sorateiden avo-ojitus', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7064, 'Sorateiden avo-ojitus (kaapeli kaivualueella)', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (5695, 'Soratien rakenne - Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7053, 'Soratien rumpujen korjaus ja uusiminen Ø> 1000 <=1200 mm', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7052, 'Soratien rumpujen korjaus ja uusiminen  Ø> 600  <=800 mm', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6933, 'Soratien rumpujen korjaus ja uusiminen  Ø <= 600 mm', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7051, 'Soratien rumpujen korjaus ja uusiminen  Ø> 800 <=1000 mm', (select o.id from maintenance_task_operation o where o.fi = 'Soratien rakenne laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Soratien rakenne'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1370, 'Auraus ja sohjonpoisto', (select o.id from maintenance_task_operation o where o.fi = 'Talvihoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Talvihoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (2862, 'Aurausviitoitus ja kinostimet', (select o.id from maintenance_task_operation o where o.fi = 'Talvihoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Talvihoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6955, 'Jäätien hoito', (select o.id from maintenance_task_operation o where o.fi = 'Talvihoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Talvihoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1365, 'Liikennemerkkien puhdistus', (select o.id from maintenance_task_operation o where o.fi = 'Talvihoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Talvihoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1367, 'Linjahiekoitus', (select o.id from maintenance_task_operation o where o.fi = 'Talvihoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Talvihoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (2863, 'Lumen siirto', (select o.id from maintenance_task_operation o where o.fi = 'Talvihoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Talvihoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1364, 'Lumivallien madaltaminen', (select o.id from maintenance_task_operation o where o.fi = 'Talvihoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Talvihoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12812, 'Muut talvihoitotyöt', (select o.id from maintenance_task_operation o where o.fi = 'Talvihoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Talvihoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (2864, 'Paannejään poisto', (select o.id from maintenance_task_operation o where o.fi = 'Talvihoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Talvihoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1366, 'Pinnan tasaus', (select o.id from maintenance_task_operation o where o.fi = 'Talvihoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Talvihoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1368, 'Pistehiekoitus', (select o.id from maintenance_task_operation o where o.fi = 'Talvihoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Talvihoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1363, 'Sulamisveden haittojen torjunta', (select o.id from maintenance_task_operation o where o.fi = 'Talvihoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Talvihoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1369, 'Suolaus', (select o.id from maintenance_task_operation o where o.fi = 'Talvihoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Talvihoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (5678, 'Talvihoito - Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Talvihoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Talvihoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6957, 'Yksikkohintainen esimerkkitehtävä', (select o.id from maintenance_task_operation o where o.fi = 'Talvihoito laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Talvihoito'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12831, 'Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Laaja toimenpide'), (select c.id from maintenance_task_category c where c.fi = 'Tiemerkintä'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1465, 'Linjamerkinnän upotusjyrsintä', (select o.id from maintenance_task_operation o where o.fi = 'Laaja toimenpide'), (select c.id from maintenance_task_category c where c.fi = 'Tiemerkintä'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1462, 'Muut pienmerkinnät', (select o.id from maintenance_task_operation o where o.fi = 'Laaja toimenpide'), (select c.id from maintenance_task_category c where c.fi = 'Tiemerkintä'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1463, 'Nuolet ja nopeusrajoitusmerkinnät ja väistämisviivat', (select o.id from maintenance_task_operation o where o.fi = 'Laaja toimenpide'), (select c.id from maintenance_task_category c where c.fi = 'Tiemerkintä'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1464, 'Sulkualueet', (select o.id from maintenance_task_operation o where o.fi = 'Laaja toimenpide'), (select c.id from maintenance_task_category c where c.fi = 'Tiemerkintä'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (5697, 'Tiemerkintä - Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Laaja toimenpide'), (select c.id from maintenance_task_category c where c.fi = 'Tiemerkintä'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12908, 'Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Laaja toimenpide'), (select c.id from maintenance_task_category c where c.fi = 'Tiesilta'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6927, 'Avattavan sillan varaosat', (select o.id from maintenance_task_operation o where o.fi = 'Tiesilta laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Tiesilta'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6928, 'Avattavien siltojen viankorjaukset', (select o.id from maintenance_task_operation o where o.fi = 'Tiesilta laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Tiesilta'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12830, 'Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Tiesilta laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Tiesilta'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (5696, 'Tiesilta - Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Tiesilta laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Tiesilta'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12879, 'Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Tieväylä laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Tieväylä'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12728, 'Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1499, 'Asentaja', (select o.id from maintenance_task_operation o where o.fi = 'Valaistuksen korjaus'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1502, 'Kuorma-auto nosturilla', (select o.id from maintenance_task_operation o where o.fi = 'Valaistuksen korjaus'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1503, 'Nostolava alle 13 m', (select o.id from maintenance_task_operation o where o.fi = 'Valaistuksen korjaus'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1504, 'Nostolava yli 13 m', (select o.id from maintenance_task_operation o where o.fi = 'Valaistuksen korjaus'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1500, 'Tr- kaivuri', (select o.id from maintenance_task_operation o where o.fi = 'Valaistuksen korjaus'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (1501, 'Törmäysvaimennin', (select o.id from maintenance_task_operation o where o.fi = 'Valaistuksen korjaus'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12827, 'Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6940, 'Kaiteen rakentaminen', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6959, 'Kaiteiden jatkaminen', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6909, 'Kaiteiden kunnostaminen', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6907, 'Kaiteiden nostaminen', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6913, 'Kaiteiden purkaminen', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6939, 'Kaiteiden uusiminen', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6937, 'Kaiteiden uusiminen/rakentaminen', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6938, 'Kaiteiden uusiminen (tuiskukaiteeksi)', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6912, 'Kiertotieopasteet', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6911, 'Kunnostettavat esteettömyyskohteet', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6930, 'Käymälöiden poisto L- ja P-alueilta', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6958, 'Lisäkilvet L- ja P- alueille', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6949, 'L- ja P-alueiden liikennemerkkien rakentaminen tukirakenteineen', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6929, 'L- ja P-opasteet (sis.putket, jalustat)', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6961, 'Pysäkkikatoksen korjaaminen', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6960, 'Pysäkkikatoksen poistaminen', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6936, 'Pysäkkikatoksen uusiminen', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6935, 'Pysäkkikatosten uusiminen, maaseudulla', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6934, 'Pysäkkikatosten uusiminen, taajamassa', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6931, 'Reunapaalujen uusiminen', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7011, 'Rumpujen korjaus ja uusiminen', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7017, 'Rumpujen korjaus ja uusiminen  600 - 1000 mm', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7016, 'Rumpujen korjaus ja uusiminen <= 600 mm', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7015, 'Rumpujen korjaus/uusiminen/rakentaminen', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7014, 'Rumpujen korj./uusiminen/rakentaminen ilman siirtymäkiilaa', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (7013, 'Rumpujen ohjelmoitu uusiminen', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6914, 'Siltojen lumiverkkojen asennus', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (6910, 'Varareittien kiertotieopastustaulut', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (5693, 'Varuste ja laite (ohjelmoidut korjaukset) - Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Varuste ja laite korjaus laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Varuste ja laite (ohjelmoidut korjaukset)'));
INSERT INTO MAINTENANCE_TASK (ID, FI, operation_id, category_id) VALUES (12797, 'Ei yksilöity', (select o.id from maintenance_task_operation o where o.fi = 'Vesiliikenteen käyttöpalvelut laaja TPI'), (select c.id from maintenance_task_category c where c.fi = 'Vesiliikenteen käyttöpalvelut'));