CREATE SEQUENCE SEQ_MAINTENANCE_REALIZATION_DATA;

CREATE TABLE IF NOT EXISTS MAINTENANCE_REALIZATION_DATA
(
    id          BIGINT NOT NULL PRIMARY KEY,
    job_id      BIGINT NOT NULL, -- harja urakka
    json        TEXT NOT NULL,
    status      VARCHAR(20) NOT NULL,
    created     TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    modified    TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE MAINTENANCE_REALIZATION_DATA is 'JOB_ID is HARJAs urakka id';

ALTER TABLE MAINTENANCE_REALIZATION_DATA
    ADD CONSTRAINT MAINTENANCE__REALIZATION_DATA_STATUS_CHECK CHECK (status IN ('UNHANDLED', 'HANDLED', 'ERROR'));

CREATE INDEX MAINTENANCE_REALIZATION_DATA_HANDLING_I
ON MAINTENANCE_REALIZATION_DATA
USING BTREE (status, id ASC) where status = 'UNHANDLED';

CREATE TRIGGER MAINTENANCE_REALIZATION_DATA_MODIFIED_T BEFORE UPDATE ON MAINTENANCE_REALIZATION_DATA FOR EACH ROW EXECUTE PROCEDURE update_modified_column();