CREATE TABLE IF NOT EXISTS V2_REALIZATION_TASK (
                                                    HARJA_ID               BIGINT PRIMARY KEY,
                                                    TASK                   TEXT   NOT NULL,
                                                    OPERATION              TEXT   NOT NULL,
                                                    OPERATION_SPECIFIER    TEXT   NOT NULL
);

-- delete from V2_WORK_MACHINE_TASK;

INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12911, 'Ei yksilöity', 'Laaja toimenpide', 'Kevyen liikenteen järjestely T');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12913, 'Ei yksilöity', 'Laaja toimenpide', 'Liikenneturvallisuustoimenpiteet');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12811, 'Ei yksilöity', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1439, 'Graffitien poisto', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1357, 'Harjaus', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6883, 'Harjaus ja roskien poisto', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1438, 'Huonokuntoisten viittojen ja opastetaulujen uusiminen', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1437, 'Hylättyjen ajoneuvojen siirto', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1436, 'Katupölynsidonta', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1435, 'Kolmannen osapuolen vahinkojen korjaukset', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6956, 'Kolmansien osapuolien vahinkojen korjaukset', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1356, 'Koneellinen niitto', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1355, 'Koneellinen vesakonraivaus', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6893, 'Liikennemerkkien, opasteiden ja liikenteenohjauslaitteiden hoito sekä reunapaalujen kp', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (5677, 'Liikenneympäristön hoito - Ei yksilöity', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1354, 'L- ja p-alueiden puhdistus', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7038, 'Luvattomien mainosten poistaminen', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1505, 'Maastopalvelu', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7062, 'Maastopartio (auto + 2 ram)', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7089, 'Meluesteiden pesu', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6926, 'Metsähakkuu tienvarresta', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1432, 'Metsän harvennus', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (2866, 'Muu liikenneympäristön hoito', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6882, 'Muut viheralueiden hoitoon liittyvät työt', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (2867, 'Nurmetuksen hoito / niitto', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1431, 'Opastinviitan tai -taulun uusiminen ja lisääminen -ajoradan yläpuoliset opasteet', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6924, 'Opastustaulujen ja opastusviittojen uusiminen portaaliin', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6989, 'Opastustaulujen ja opastusviittojen uusiminen -portaalissa olevan viitan/opastetaulun uusiminen', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1429, 'Opastustaulujen ja opastusviittojen uusiminen -porttaalissa olevan viitan/opastetaulun uusiminen', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1428, 'Opastustaulujen ja opastusviittojen uusiminen -vanhan viitan/opastetaulun uusiminen', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1427, 'Opastustaulujen ja opastusviittojen uusiminen -vanhan viitan/opastetaulun uusiminen/uuden asentaminen tukirakenteineen', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1426, 'Pensaiden poisto', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1425, 'Pensaiden täydennysistutus', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6898, 'Porttaalien tarkastus ja huolto', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1424, 'Porttaalien vuositarkastus', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (2865, 'Puiden ja pensaiden hoito', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1423, 'Puun poisto raivausjätteineen (taajaman ulkopuolella)', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1422, 'Puun poisto raivausjätteineen (taajamassa)', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6992, 'Pysäkkikatosten hoito, tavanomaiset sis. talvi- ja kesähoidon sekä rakenteiden huoltamisen (uudet)', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6991, 'Pysäkkikatosten hoito, vilkkaat sis. talvi- ja kesähoidon sekä rakenteiden huoltamisen (uudet)', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7044, 'Pysäkkikatosten oikaisu', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7043, 'Pysäkkikatosten tarkastus, kunnostus ja huoltomaalaus', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6869, 'Päällystettyjen teiden palteen poisto', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1414, 'Päällystettyjen teiden palteiden poisto', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1411, 'Päällystettyjen teiden sorapientareen kunnossapito', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7067, 'Päällystettyjen teiden sorapientareen täyttö', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6881, 'Risteysalueiden näkemäraivaus', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6999, 'Roskien poisto ja kevätsiivoukset L- ja P-alueilta', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6997, 'Roskien poisto ja kevätsiivoukset muut tiet', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6998, 'Roskien poisto ja kevätsiivoukset taajamat, kevarit ja päätiet', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6899, 'Rumpujen aukaisu ja muut rumpujen hoitoon liittyvät työt', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1407, 'Rumpujen korjaus ja uusiminen', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1406, 'Rumpujen korjaus ja uusiminen  600 - 1000 mm', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1405, 'Rumpujen korjaus ja uusiminen <= 600 mm', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6943, 'Rumpujen korjaus ja uusiminen  Ø> 600 - 1000 mm', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6945, 'Rumpujen korjaus ja uusiminen  ≤Ø 600 mm', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1404, 'Rumpujen korjaus/uusiminen/rakentaminen', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1408, 'Rumpujen korj./uusiminen/rakentaminen ilman siirtymäkiilaa', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1403, 'Runkopuiden poisto', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1402, 'Runkopuiden täydennysistutus', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (2868, 'Siltojen ja laitureiden puhdistus', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1398, 'Siltojen vuositarkastus', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1396, 'Sisääntuloteiden siisteyden varmistaminen', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1395, 'Tunnelin laitteiden toimivuuden testaukset', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1394, 'Tunnelin paikalliskeskuksen hoito', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1393, 'Tunnelin pesu ja muu puhtaanapito', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1392, 'Tunnelin pumppaamon poistoputken pään laskuojan huolto', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6900, 'Tunnelin vikakorjaukset, 2 rakennusammattimies', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6953, 'Vakiokokoisten liikennemerkkien uusiminen ja lisääminen merkki tukirakenteineen (60 mm varsi)', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6903, 'Vakiokokoisten liikennemerkkien uusiminen ja lisääminen merkki tukirakenteineen (90 mm varsi)', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6902, 'Vakiokokoisten liikennemerkkien uusiminen, merkin vaihto tukirakenteineen', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7000, 'Valvontakameratolppien puhdistus/tarkistus keväisin', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1391, 'Vesakonraivaus/ha', 'Liikenneympäristön hoito laaja TPI', 'Liikenneympäristön hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12826, 'Ei yksilöity', 'Liikenneympäristön parantaminen laaja TPI', 'Liikenneympäristön parantaminen');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6932, 'Liikennesaarekkeen kunnostus', 'Liikenneympäristön parantaminen laaja TPI', 'Liikenneympäristön parantaminen');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (5692, 'Liikenneympäristön parantaminen - Ei yksilöity', 'Liikenneympäristön parantaminen laaja TPI', 'Liikenneympäristön parantaminen');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7055, 'Sorapintaisten jk+pp -teiden kesähoito', 'MHU ja HJU Hoidon johto', 'MHU ja HJU hoidon johto');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12825, 'Ei yksilöity', 'Laaja toimenpide', 'MHU Ylläpito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (5691, 'Projektiin liittyvä suunnittelu-, teettämis-, ja valvontapalvelu - Ei yksilöity', 'Laaja toimenpide', 'MHU Ylläpito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12809, 'Ei yksilöity', 'Laaja toimenpide', 'Projektiin liittyvä suunnittelu-, teettämis-, ja valvontapalvelu');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (5675, 'Projektiin liittyvä suunnittelu-, teettämis-, ja valvontapalvelu - Ei yksilöity', 'Laaja toimenpide', 'Projektiin liittyvä suunnittelu-, teettämis-, ja valvontapalvelu');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14524, 'Kuumapäällyste, ab käsityönä', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14525, 'Kuumapäällyste, valuasfaltti', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14526, 'Päällysteen korjaus mastiksilla siltakohteiden heitoissa', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14527, 'Päällysteiden paikkaus - Konetiivistetty massasaumaus 20 cm leveä', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14528, 'Päällysteiden paikkaus - konetiivistetty -valuasfaltti', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14529, 'Päällysteiden paikkaus - kuumapäällyste', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14542, 'Päällysteiden paikkaus, kylmäpäällyste', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14530, 'Päällysteiden paikkaus - massasaumaus', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14541, 'Päällysteiden paikkaus -saumojen juottaminen mastiksilla', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14531, 'Päällysteiden paikkaus - valuasfaltti', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14544, 'Reunapalkin ja päällysteen välisen sauman tiivistäminen', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14543, 'Reunapalkin ja päällysteen väl. sauman tiivistäminen', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14545, 'Reunapalkin liikuntasauman tiivistäminen', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14546, 'Sillan kannen päällysteen päätysauman korjaukset', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14547, 'Sillan päällysteen halkeaman avarrussaumaus', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14548, 'Sillan päällysteen halkeaman sulkeminen', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (14549, 'SIP paikkaus (kesto+kylmä)', 'Päällystepaikkaukset laaja TPI', 'Päällyste');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6901, 'Avo-ojitus / päällystetyt muut tiet ja soratiet', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7054, 'Avo-ojitus / päällystetyt tiet', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7090, 'Avo-ojitus/päällystetyt tiet (kaapeli kaivualueella)', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6918, 'Avo-ojitus / päällystetyt vt-, kt- ja seututiet', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12832, 'Ei yksilöity', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7009, 'Laskuojat/päällystetyt tiet', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7056, 'Päällystettyjen teiden pölynsidonta', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6916, 'Päällystettyjen teiden rumpujen ohjelmoitu uusiminen 1000 mm', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6915, 'Päällystettyjen teiden rumpujen ohjelmoitu uusiminen 1200 mm', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6917, 'Päällystettyjen teiden rumpujen ohjelmoitu uusiminen 800 mm', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6919, 'Päällystetyn tien avo-ojitus', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7039, 'Päällystetyn tien rumpujen korjaus ja uusiminen Ø> 1000 <= 1200 mm', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6905, 'Päällystetyn tien rumpujen korjaus ja uusiminen  Ø> 600  <= 800 mm', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6906, 'Päällystetyn tien rumpujen korjaus ja uusiminen Ø <= 600 mm', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6904, 'Päällystetyn tien rumpujen korjaus ja uusiminen  Ø> 800 <= 1000 mm', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (5698, 'Päällystetyn tien tierakenne - Ei yksilöity', 'Päällystetyn tien rakenne laaja TPI', 'Päällystetyn tien tierakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (5676, 'Alueurakan soratien hoito - Ei yksilöity', 'Soratien hoito laaja TPI', 'Soratien hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6925, 'Liikenteen varmistaminen kelirikkokohteessa', 'Soratien hoito laaja TPI', 'Soratien hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12810, 'Muut sorateiden hoitoon liittyvät tehtävät', 'Soratien hoito laaja TPI', 'Soratien hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7008, 'Oja- ja luiskameteriaalin käyttö kulutuskerrokseeen', 'Soratien hoito laaja TPI', 'Soratien hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7012, 'Rumpujen ohjelmoitu uusiminen', 'Soratien hoito laaja TPI', 'Soratien hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1359, 'Sorastus km', 'Soratien hoito laaja TPI', 'Soratien hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1389, 'Sorateiden kaventaminen', 'Soratien hoito laaja TPI', 'Soratien hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1362, 'Sorateiden muokkaushöyläys', 'Soratien hoito laaja TPI', 'Soratien hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (2869, 'Sorateiden pinnan hoito', 'Soratien hoito laaja TPI', 'Soratien hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1361, 'Sorateiden pölynsidonta', 'Soratien hoito laaja TPI', 'Soratien hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1360, 'Sorateiden tasaus', 'Soratien hoito laaja TPI', 'Soratien hoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12829, 'Ei yksilöity', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7048, 'Kallion leikkaus ja maakivien poisto', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7050, 'Laskuojat/soratiet', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6921, 'Maakivien poisto', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7049, 'Ojitusmaiden ajo läjitykseen', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7047, 'Päällysteen purku/ muuttaminen soratieksi', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6965, 'Rummun uusiminen >600 ilman kiiloja (max 1000) sorateillä', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6964, 'Rummun uusiminen >600 kiiloineen (max 1000) sorateillä', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6952, 'Rumpujen rakentaminen sorateille siirtymäkiilalla', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7063, 'Sorapintaisten jk+pp -teiden kesähoito', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6950, 'Sorateiden avo-ojitus', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7064, 'Sorateiden avo-ojitus (kaapeli kaivualueella)', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (5695, 'Soratien rakenne - Ei yksilöity', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7053, 'Soratien rumpujen korjaus ja uusiminen Ø> 1000 <=1200 mm', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7052, 'Soratien rumpujen korjaus ja uusiminen  Ø> 600  <=800 mm', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6933, 'Soratien rumpujen korjaus ja uusiminen  Ø <= 600 mm', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7051, 'Soratien rumpujen korjaus ja uusiminen  Ø> 800 <=1000 mm', 'Soratien rakenne laaja TPI', 'Soratien rakenne');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1370, 'Auraus ja sohjonpoisto', 'Talvihoito laaja TPI', 'Talvihoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (2862, 'Aurausviitoitus ja kinostimet', 'Talvihoito laaja TPI', 'Talvihoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6955, 'Jäätien hoito', 'Talvihoito laaja TPI', 'Talvihoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1365, 'Liikennemerkkien puhdistus', 'Talvihoito laaja TPI', 'Talvihoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1367, 'Linjahiekoitus', 'Talvihoito laaja TPI', 'Talvihoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (2863, 'Lumen siirto', 'Talvihoito laaja TPI', 'Talvihoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1364, 'Lumivallien madaltaminen', 'Talvihoito laaja TPI', 'Talvihoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12812, 'Muut talvihoitotyöt', 'Talvihoito laaja TPI', 'Talvihoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (2864, 'Paannejään poisto', 'Talvihoito laaja TPI', 'Talvihoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1366, 'Pinnan tasaus', 'Talvihoito laaja TPI', 'Talvihoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1368, 'Pistehiekoitus', 'Talvihoito laaja TPI', 'Talvihoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1363, 'Sulamisveden haittojen torjunta', 'Talvihoito laaja TPI', 'Talvihoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1369, 'Suolaus', 'Talvihoito laaja TPI', 'Talvihoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (5678, 'Talvihoito - Ei yksilöity', 'Talvihoito laaja TPI', 'Talvihoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6957, 'Yksikkohintainen esimerkkitehtävä', 'Talvihoito laaja TPI', 'Talvihoito');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12831, 'Ei yksilöity', 'Laaja toimenpide', 'Tiemerkintä');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1465, 'Linjamerkinnän upotusjyrsintä', 'Laaja toimenpide', 'Tiemerkintä');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1462, 'Muut pienmerkinnät', 'Laaja toimenpide', 'Tiemerkintä');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1463, 'Nuolet ja nopeusrajoitusmerkinnät ja väistämisviivat', 'Laaja toimenpide', 'Tiemerkintä');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1464, 'Sulkualueet', 'Laaja toimenpide', 'Tiemerkintä');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (5697, 'Tiemerkintä - Ei yksilöity', 'Laaja toimenpide', 'Tiemerkintä');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12908, 'Ei yksilöity', 'Laaja toimenpide', 'Tiesilta');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6927, 'Avattavan sillan varaosat', 'Tiesilta laaja TPI', 'Tiesilta');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6928, 'Avattavien siltojen viankorjaukset', 'Tiesilta laaja TPI', 'Tiesilta');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12830, 'Ei yksilöity', 'Tiesilta laaja TPI', 'Tiesilta');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (5696, 'Tiesilta - Ei yksilöity', 'Tiesilta laaja TPI', 'Tiesilta');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12879, 'Ei yksilöity', 'Tieväylä laaja TPI', 'Tieväylä');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12728, 'Ei yksilöity', 'Varuste ja laite laaja TPI', 'Varuste ja laite');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1499, 'Asentaja', 'Valaistuksen korjaus', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1502, 'Kuorma-auto nosturilla', 'Valaistuksen korjaus', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1503, 'Nostolava alle 13 m', 'Valaistuksen korjaus', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1504, 'Nostolava yli 13 m', 'Valaistuksen korjaus', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1500, 'Tr- kaivuri', 'Valaistuksen korjaus', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (1501, 'Törmäysvaimennin', 'Valaistuksen korjaus', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12827, 'Ei yksilöity', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6940, 'Kaiteen rakentaminen', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6959, 'Kaiteiden jatkaminen', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6909, 'Kaiteiden kunnostaminen', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6907, 'Kaiteiden nostaminen', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6913, 'Kaiteiden purkaminen', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6939, 'Kaiteiden uusiminen', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6937, 'Kaiteiden uusiminen/rakentaminen', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6938, 'Kaiteiden uusiminen (tuiskukaiteeksi)', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6912, 'Kiertotieopasteet', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6911, 'Kunnostettavat esteettömyyskohteet', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6930, 'Käymälöiden poisto L- ja P-alueilta', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6958, 'Lisäkilvet L- ja P- alueille', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6949, 'L- ja P-alueiden liikennemerkkien rakentaminen tukirakenteineen', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6929, 'L- ja P-opasteet (sis.putket, jalustat)', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6961, 'Pysäkkikatoksen korjaaminen', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6960, 'Pysäkkikatoksen poistaminen', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6936, 'Pysäkkikatoksen uusiminen', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6935, 'Pysäkkikatosten uusiminen, maaseudulla', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6934, 'Pysäkkikatosten uusiminen, taajamassa', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6931, 'Reunapaalujen uusiminen', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7011, 'Rumpujen korjaus ja uusiminen', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7017, 'Rumpujen korjaus ja uusiminen  600 - 1000 mm', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7016, 'Rumpujen korjaus ja uusiminen <= 600 mm', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7015, 'Rumpujen korjaus/uusiminen/rakentaminen', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7014, 'Rumpujen korj./uusiminen/rakentaminen ilman siirtymäkiilaa', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (7013, 'Rumpujen ohjelmoitu uusiminen', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6914, 'Siltojen lumiverkkojen asennus', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (6910, 'Varareittien kiertotieopastustaulut', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (5693, 'Varuste ja laite (ohjelmoidut korjaukset) - Ei yksilöity', 'Varuste ja laite korjaus laaja TPI', 'Varuste ja laite (ohjelmoidut korjaukset)');
INSERT INTO V2_REALIZATION_TASK (HARJA_ID, TASK, OPERATION, OPERATION_SPECIFIER) VALUES (12797, 'Ei yksilöity', 'Vesiliikenteen käyttöpalvelut laaja TPI', 'Vesiliikenteen käyttöpalvelut');