CREATE SEQUENCE SEQ_TMS_SENSOR_CONSTANT;
CREATE SEQUENCE SEQ_TMS_SENSOR_CONSTANT_VALUE;

CREATE TABLE TMS_SENSOR_CONSTANT
(
  ID                  BIGINT,
  LOTJU_ID            BIGINT NOT NULL,
  ROAD_STATION_ID     BIGINT NOT NULL,
  NAME                TEXT,
  OBSOLETE_DATE       TIMESTAMP(0) WITH TIME ZONE
  CONSTRAINT TMS_SENSOR_CONSTANT_PKEY PRIMARY KEY (id),
  CONSTRAINT U_TMS_SENSOR_CONSTANT UNIQUE(ROAD_STATION_ID, NAME)
);

CREATE TABLE TMS_SENSOR_CONSTANT_VALUE
(
  ID                  BIGINT,
  SENSOR_CONSTANT_ID  BIGINT NOT NULL REFERENCES TMS_SENSOR_CONSTANT (ID),
  VALUE               INT,
  VALID_FROM          INT,
  VALID_TO            INT,
  CONSTRAINT TMS_SENSOR_CONSTANT_VALUE_PKEY PRIMARY KEY (id)
);

