CREATE SEQUENCE SEQ_MAINTENANCE_TRACKING_DATA;

CREATE TABLE IF NOT EXISTS MAINTENANCE_TRACKING_DATA
(
    id              BIGINT NOT NULL PRIMARY KEY,
    json            TEXT NOT NULL,
    status          VARCHAR(20) NOT NULL,
    handling_info   TEXT,
    created         TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    modified        TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE MAINTENANCE_TRACKING_DATA
    ADD CONSTRAINT MAINTENANCE_TRACKING_DATA_STATUS_CHECK CHECK (status IN ('UNHANDLED', 'HANDLED', 'ERROR'));

CREATE INDEX MAINTENANCE_TRACKING_DATA_HANDLING_I
ON MAINTENANCE_TRACKING_DATA
USING BTREE (status, id ASC) where status = 'UNHANDLED';

CREATE TRIGGER MAINTENANCE_TRACKING_DATA_MODIFIED_T BEFORE UPDATE ON MAINTENANCE_TRACKING_DATA FOR EACH ROW EXECUTE PROCEDURE update_modified_column();