CREATE SEQUENCE IF NOT EXISTS SEQ_MAINTENANCE_TRACKING_OBSERVATION_DATA;

CREATE TABLE IF NOT EXISTS MAINTENANCE_TRACKING_OBSERVATION_DATA
(
    id                      BIGINT NOT NULL PRIMARY KEY,
    observation_time        TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    sending_time            TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    created                 TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    modified                TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    json                    TEXT NOT NULL,
    harja_workmachine_id    BIGINT NOT NULL,
    harja_contract_id       BIGINT NOT NULL,
    sending_system          TEXT NOT NULL,
    status                  VARCHAR(20) NOT NULL,
    handling_info           TEXT,
    hash                    TEXT NOT NULL,
    s3_uri                  TEXT NOT NULL
);

ALTER TABLE MAINTENANCE_TRACKING_OBSERVATION_DATA DROP CONSTRAINT IF EXISTS MAINTENANCE_TRACKING_OBSERVATION_DATA_STATUS_CHECK;
ALTER TABLE MAINTENANCE_TRACKING_OBSERVATION_DATA
    ADD CONSTRAINT MAINTENANCE_TRACKING_OBSERVATION_DATA_STATUS_CHECK CHECK (status IN ('UNHANDLED', 'HANDLED', 'ERROR'));

DROP INDEX IF EXISTS MAINTENANCE_TRACKING_OBSERVATION_DATA_HANDLING_ORDER_I;
CREATE INDEX MAINTENANCE_TRACKING_OBSERVATION_DATA_HANDLING_ORDER_I
    ON MAINTENANCE_TRACKING_OBSERVATION_DATA
        USING BTREE (observation_time ASC, id ASC) where status = 'UNHANDLED';

DROP TRIGGER IF EXISTS MAINTENANCE_TRACKING_OBSERVATION_DATA_MODIFIED_T ON MAINTENANCE_TRACKING_OBSERVATION_DATA;
CREATE TRIGGER MAINTENANCE_TRACKING_OBSERVATION_DATA_MODIFIED_T BEFORE UPDATE ON MAINTENANCE_TRACKING_OBSERVATION_DATA FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

DROP INDEX IF EXISTS maintenance_tracking_observation_data_hash_ui;
CREATE UNIQUE INDEX maintenance_tracking_observation_data_hash_ui on maintenance_tracking_observation_data(hash);

-- many-to-many data <-> tracking
CREATE TABLE IF NOT EXISTS MAINTENANCE_TRACKING_OBSERVATION_DATA_TRACKING
(
    data_id         BIGINT
        REFERENCES MAINTENANCE_TRACKING_OBSERVATION_DATA(id) ON DELETE CASCADE NOT NULL,
    tracking_id     BIGINT
        REFERENCES MAINTENANCE_TRACKING(id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY(data_id, tracking_id)
);

DROP INDEX IF EXISTS MAINTENANCE_TRACKING_OBSERVATION_DATA_TRACKING_TRACKING_FKEY_I;
CREATE INDEX MAINTENANCE_TRACKING_OBSERVATION_DATA_TRACKING_TRACKING_FKEY_I ON MAINTENANCE_TRACKING_OBSERVATION_DATA_TRACKING USING BTREE (tracking_id, data_id);
DROP INDEX IF EXISTS MAINTENANCE_TRACKING_OBSERVATION_DATA_TRACKING_DATA_FKEY_I;
CREATE INDEX MAINTENANCE_TRACKING_OBSERVATION_DATA_TRACKING_DATA_FKEY_I ON MAINTENANCE_TRACKING_OBSERVATION_DATA_TRACKING USING BTREE (data_id);