INSERT INTO maintenance_tracking_task_value (name, name_harja, name_fi, name_sv, name_en)
VALUES
    ('BRUSHING', 'HARJAUS', 'Harjaus', 'Borstning', 'Brushing'),
    ('BRUSH_CLEARING', 'KONEELLINEN_VESAKONRAIVAUS', 'Koneellinen vesakonraivaus', 'Slyklippning', 'Brush clearing'),
    ('CLEANSING_OF_BRIDGES', 'SILTOJEN_PUHDISTUS', 'Siltojen puhdistus', 'Rengöring av broar', 'Cleansing of bridges'),
    ('CLEANSING_OF_REST_AREAS', 'L_JA_P_ALUEIDEN_PUHDISTUS', 'L- ja p-alueiden puhdistus', 'Rast- och parkeringsplatsernas rengöring', 'Cleansing of rest areas'),
    ('CLEANSING_OF_TRAFFIC_SIGNS', 'LIIKENNEMERKKIEN_PUHDISTUS', 'Liikennemerkkien puhdistus', 'Rengöring av trafikmärken', 'Cleansing of traffic signs'),
    ('CLIENTS_QUALITY_CONTROL', 'TILAAJAN_LAADUNVALVONTA', 'Tilaajan laadunvalvonta', 'Beställarens kvalitetsövervakning', 'Clients quality control'),
    ('COMPACTION_BY_ROLLING', 'JYRAYS', 'Jyräys', 'Vibrering', 'Compaction by rolling'),
    ('CRACK_FILLING', 'PAALLYSTEIDEN_JUOTOSTYOT', 'Päällysteiden juotostyöt', 'Fyllning av sprickor i beläggningen', 'Crack filling'),
    ('DITCHING', 'OJITUS', 'Ojitus', 'Dikning', 'Ditching'),
    ('DUST_BINDING_OF_GRAVEL_ROAD_SURFACE', 'SORATEIDEN_POLYNSIDONTA', 'Sorateiden pölynsidonta', 'Dammbindning av grusväg', 'Dust binding of gravel road surface'),
    ('FILLING_OF_GRAVEL_ROAD_SHOULDERS', 'SORAPIENTAREEN_TAYTTO', 'Sorapientareen täyttö', 'Fyllning av gruskanter', 'Filling of gravel road shoulders'),
    ('FILLING_OF_ROAD_SHOULDERS', 'PAALLYSTETYN_TIEN_SORAPIENTAREEN_TAYTTO', 'Päällystetyn tien sorapientareen täyttö', 'Belagda vägars kantfyllning', 'Filling of road shoulders'),
    ('HEATING', 'KUUMENNUS', 'Kuumennus', 'Upphettning', 'Heating'),
    ('LEVELLING_GRAVEL_ROAD_SURFACE', 'SORATEIDEN_TASAUS', 'Sorateiden tasaus', 'Utjämning av grusväg', 'Levelling gravel road surface'),
    ('LEVELLING_OF_ROAD_SHOULDERS', 'PALTEEN_POISTO', 'Palteen poisto', 'Kantskärning', 'Levelling of road shoulders'),
    ('LEVELLING_OF_ROAD_SURFACE', 'PINNAN_TASAUS', 'Pinnan tasaus', 'Utjämning av vägytan', 'Levelling of road surface'),
    ('LINE_SANDING', 'LINJAHIEKOITUS', 'Linjahiekoitus', 'Linjesandning', 'Line sanding'),
    ('LOWERING_OF_SNOWBANKS', 'LUMIVALLIEN_MADALTAMINEN', 'Lumivallien madaltaminen', 'Nedsänkning av plogvall', 'Lowering of snowbanks'),
    ('MAINTENANCE_OF_GUIDE_SIGNS_AND_REFLECTOR_POSTS', 'LIIK_OPAST_JA_OHJAUSL_HOITO_SEKA_REUNAPAALUJEN_KUN_PITO', 'Liikenteen opasteiden ja ohjauslaitteiden hoito sekä reunapaalujen kunnossapito', 'Trafikanordningars och kantpålars underhåll', 'Maintenance of guide signs and reflector posts'),
    ('MECHANICAL_CUT', 'KONEELLINEN_NIITTO', 'Koneellinen niitto', 'Mekanisk klippning', 'Mechanical cut'),
    ('MIXING_OR_STABILIZATION', 'SEKOITUS_TAI_STABILOINTI', 'Sekoitus tai stabilointi', 'Blandning och stabilisering', 'Mixing or stabilization'),
    ('OTHER', 'MUU', 'Muu', 'Annat dylikt', 'Other'),
    ('PATCHING', 'PAALLYSTEIDEN_PAIKKAUS', 'Päällysteiden paikkaus', 'Lappning av beläggning', 'Patching'),
    ('PAVING', 'ASFALTOINTI', 'Asfaltointi', 'Asfaltering', 'Paving'),
    ('PLOUGHING_AND_SLUSH_REMOVAL', 'AURAUS_JA_SOHJONPOISTO', 'Auraus ja sohjonpoisto', 'Plog- och sörjröjning', 'Ploughing and slush removal'),
    ('PREVENTING_MELTING_WATER_PROBLEMS', 'SULAMISVEDEN_HAITTOJEN_TORJUNTA', 'Sulamisveden haittojen torjunta', 'Smältvattensbekämpning', 'Preventing melting water problems'),
    ('REMOVAL_OF_BULGE_ICE', 'PAANNEJAAN_POISTO', 'Paannejään poisto', 'Borttagning av svall-is', 'Removal of bulge ice'),
    ('RESHAPING_GRAVEL_ROAD_SURFACE', 'SORATEIDEN_MUOKKAUSHOYLAYS', 'Sorateiden muokkaushöyläys', 'Grusvägsytans omblandning ', 'Reshaping gravel road surface'),
    ('ROAD_INSPECTIONS', 'TIESTOTARKASTUS', 'Tiestötarkastus', 'Väggranskning', 'Road inspections '),
    ('ROAD_MARKINGS', 'TIEMERKINTA', 'Tiemerkintä', 'Vägmarkering', 'Road markings'),
    ('ROAD_STATE_CHECKING', 'KELINTARKASTUS', 'Kelintarkastus', 'Väglagsgranskning', 'Road state checking'),
    ('SAFETY_EQUIPMENT', 'TURVALAITE', 'Turvalaite', 'Säkerhetsanordning', 'Safety equipment'),
    ('SALTING', 'SUOLAUS', 'Suolaus', 'Saltning', 'Salting'),
    ('SNOW_PLOUGHING_STICKS_AND_SNOW_FENCES', 'AURAUSVIITOITUS_JA_KINOSTIMET', 'Aurausviitoitus ja kinostimet', 'Plogkäppsmarkering och snödrivor', 'Snow-ploughing sticks and snow fences'),
    ('SPOT_SANDING', 'PISTEHIEKOITUS', 'Pistehiekoitus', 'Punktsandning', 'Spot sanding'),
    ('SPREADING_OF_CRUSH', 'SORASTUS', 'Sorastus', 'Grusning', 'Spreading of crush'),
    ('TRANSFER_OF_SNOW', 'LUMENSIIRTO', 'Lumensiirto', 'Bortforsling av snömassor', 'Transfer of snow'),
    ('UNKNOWN', 'TUNTEMATON', 'Tuntematon', 'Obekant', 'Unknown')
    on conflict (name) do nothing;