CREATE TABLE MAINTENANCE_TRACKING_TASK (
    MAINTENANCE_TRACKING_ID   BIGINT NOT NULL,
    TASK                       TEXT NOT NULL,
    PRIMARY KEY(MAINTENANCE_TRACKING_ID, TASK),
    FOREIGN KEY (MAINTENANCE_TRACKING_ID)
       REFERENCES MAINTENANCE_TRACKING(ID)
);