 --select 'insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (' || sensor_id || ',' ||
 --sensor_value || ',''' || description_fi || ''',''' || description_en || ''');' from sensor_value_description;

insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (18,0,'Pouta','Dry weather');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (18,1,'Heikko','Weak');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (18,2,'Kohtalainen','Moderate');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (18,3,'Runsas','Abundant');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (18,4,'Heikko lumi/räntä','Light snow/sleet');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (18,5,'Kohtalainen lumi/räntä','Moderate snow/sleet');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (18,6,'Runsas lumi/räntä','Abundant snow/sleet');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (21,7,'Pouta','Dry weather');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (21,8,'Hyvin heikko sade, olomuotoa ei voida päätellä','Very light rain, state cannot be determined');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (21,9,'Tihku','Drizzle');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (21,10,'Vesisade','Rain');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (21,11,'Lumisade','Snowfall');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (21,12,'Märkä räntä','Wet sleet');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (21,13,'Räntä','Sleet');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (21,14,'Rakeita','Hails');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (21,15,'Jääkiteitä','Ice crystals');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (21,16,'Lumijyväsiä','Snow grains');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (21,17,'Lumirakeita','Graupel');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (21,18,'Jäätävä tihku','Freezing drizzle');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (21,19,'Jäätävä sade','Freezing rain');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (23,0,'Anturissa on vikaa','The sensor has a fault');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (23,1,'Kuiva','Dry');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (23,2,'Kostea','Moist');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (23,3,'Märkä','Wet');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (23,4,'Märkä ja suolattu','Wet and salty');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (23,5,'Kuura','Frost');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (23,6,'Lumi','Snow');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (23,7,'Jää','Ice');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (23,8,'Todennäköisesti kostea ja suolainen','Probably moist and salty');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (24,0,'Anturissa on vikaa','The sensor has a fault');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (24,1,'Kuiva','Dry');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (24,2,'Kostea','Moist');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (24,3,'Märkä','Wet');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (24,4,'Märkä ja suolattu','Wet and salty');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (24,5,'Kuura','Frost');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (24,6,'Lumi','Snow');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (24,7,'Jää','Ice');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (24,8,'Todennäköisesti kostea ja suolainen','Probably moist and salty');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (25,0,'OK','OK');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (25,1,'Varo','Beware');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (25,2,'Häly','Alarm');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (25,3,'Kuura','Frost');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (25,4,'Sade','Rain');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (26,0,'OK','OK');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (26,1,'Varo','Beware');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (26,2,'Häly','Alarm');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (26,3,'Kuura','Frost');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (26,4,'Sade','Rain');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (53,0,'OK','OK');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (53,1,'Varo','Beware');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (53,2,'Häly','Alarm');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (53,3,'Kuura','Frost');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (53,4,'Sade','Rain');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (24,9,'Sohjoinen','Slushy');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (23,9,'Sohjoinen','Slushy');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (1,0,'OK','OK');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (1,1,'Vikaepäily','Suspected malfunction');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (1,2,'Vika vahvistettu','Confirmed malfunction');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (1,3,'Vika vahvistettu, mutta ei korjata lähiaikoina','Confirmed malfunction, repair not planned in near future');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (1,4,'Huolto tilattu','Maintenance request sent');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (1,5,'Huolto tehty','Maintenance work done');
insert into sensor_value_description(sensor_id, sensor_value, description_fi, description_en) values (1,6,'Huolto keskeytetty','Maintenance work interrupted');