INSERT INTO ROAD_STATION_TYPE (ROAD_STATION_TYPE, TYPE) VALUES ('TMS_STATION', 1);
INSERT INTO ROAD_STATION_TYPE (ROAD_STATION_TYPE, TYPE) VALUES ('WEATHER_STATION', 2);
INSERT INTO ROAD_STATION_TYPE (ROAD_STATION_TYPE, TYPE) VALUES ('CAMERA_STATION', 3);