// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lam_realtime.proto

package fi.ely.lotju.lam.proto;

public final class LAMRealtimeProtos {
  private LAMRealtimeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lam.Lam)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 asemaId = 1;</code>
     */
    boolean hasAsemaId();
    /**
     * <code>required int64 asemaId = 1;</code>
     */
    long getAsemaId();

    /**
     * <code>required int64 aika = 2;</code>
     */
    boolean hasAika();
    /**
     * <code>required int64 aika = 2;</code>
     */
    long getAika();

    /**
     * <code>required bool isRealtime = 3 [default = true];</code>
     */
    boolean hasIsRealtime();
    /**
     * <code>required bool isRealtime = 3 [default = true];</code>
     */
    boolean getIsRealtime();

    /**
     * <code>required bool isNollaOhitus = 4 [default = false];</code>
     */
    boolean hasIsNollaOhitus();
    /**
     * <code>required bool isNollaOhitus = 4 [default = false];</code>
     */
    boolean getIsNollaOhitus();

    /**
     * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
     */
    java.util.List<Lam.Anturi>
        getAnturiList();
    /**
     * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
     */
    Lam.Anturi getAnturi(int index);
    /**
     * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
     */
    int getAnturiCount();
    /**
     * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
     */
    java.util.List<? extends Lam.AnturiOrBuilder>
        getAnturiOrBuilderList();
    /**
     * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
     */
    Lam.AnturiOrBuilder getAnturiOrBuilder(int index);
  }
  /**
   * Protobuf type {@code lam.Lam}
   */
  public  static final class Lam extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lam.Lam)
      LamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Lam.newBuilder() to construct.
    private Lam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Lam() {
      asemaId_ = 0L;
      aika_ = 0L;
      isRealtime_ = true;
      isNollaOhitus_ = false;
      anturi_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Lam(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              asemaId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              aika_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isRealtime_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              isNollaOhitus_ = input.readBool();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                anturi_ = new java.util.ArrayList<Anturi>();
                mutable_bitField0_ |= 0x00000010;
              }
              anturi_.add(
                  input.readMessage(Anturi.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          anturi_ = java.util.Collections.unmodifiableList(anturi_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LAMRealtimeProtos.internal_static_lam_Lam_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LAMRealtimeProtos.internal_static_lam_Lam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Lam.class, Builder.class);
    }

    public interface AnturiOrBuilder extends
        // @@protoc_insertion_point(interface_extends:lam.Lam.Anturi)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int64 laskennallinenAnturiId = 1;</code>
       */
      boolean hasLaskennallinenAnturiId();
      /**
       * <code>required int64 laskennallinenAnturiId = 1;</code>
       */
      long getLaskennallinenAnturiId();

      /**
       * <code>required int32 arvo = 2;</code>
       */
      boolean hasArvo();
      /**
       * <code>required int32 arvo = 2;</code>
       */
      int getArvo();

      /**
       * <code>optional int64 aikaikkunaAlku = 3;</code>
       */
      boolean hasAikaikkunaAlku();
      /**
       * <code>optional int64 aikaikkunaAlku = 3;</code>
       */
      long getAikaikkunaAlku();

      /**
       * <code>optional int64 aikaikkunaLoppu = 4;</code>
       */
      boolean hasAikaikkunaLoppu();
      /**
       * <code>optional int64 aikaikkunaLoppu = 4;</code>
       */
      long getAikaikkunaLoppu();
    }
    /**
     * Protobuf type {@code lam.Lam.Anturi}
     */
    public  static final class Anturi extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:lam.Lam.Anturi)
        AnturiOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Anturi.newBuilder() to construct.
      private Anturi(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Anturi() {
        laskennallinenAnturiId_ = 0L;
        arvo_ = 0;
        aikaikkunaAlku_ = 0L;
        aikaikkunaLoppu_ = 0L;
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Anturi(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                laskennallinenAnturiId_ = input.readInt64();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                arvo_ = input.readInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                aikaikkunaAlku_ = input.readInt64();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                aikaikkunaLoppu_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LAMRealtimeProtos.internal_static_lam_Lam_Anturi_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LAMRealtimeProtos.internal_static_lam_Lam_Anturi_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Anturi.class, Builder.class);
      }

      private int bitField0_;
      public static final int LASKENNALLINENANTURIID_FIELD_NUMBER = 1;
      private long laskennallinenAnturiId_;
      /**
       * <code>required int64 laskennallinenAnturiId = 1;</code>
       */
      public boolean hasLaskennallinenAnturiId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 laskennallinenAnturiId = 1;</code>
       */
      public long getLaskennallinenAnturiId() {
        return laskennallinenAnturiId_;
      }

      public static final int ARVO_FIELD_NUMBER = 2;
      private int arvo_;
      /**
       * <code>required int32 arvo = 2;</code>
       */
      public boolean hasArvo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 arvo = 2;</code>
       */
      public int getArvo() {
        return arvo_;
      }

      public static final int AIKAIKKUNAALKU_FIELD_NUMBER = 3;
      private long aikaikkunaAlku_;
      /**
       * <code>optional int64 aikaikkunaAlku = 3;</code>
       */
      public boolean hasAikaikkunaAlku() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 aikaikkunaAlku = 3;</code>
       */
      public long getAikaikkunaAlku() {
        return aikaikkunaAlku_;
      }

      public static final int AIKAIKKUNALOPPU_FIELD_NUMBER = 4;
      private long aikaikkunaLoppu_;
      /**
       * <code>optional int64 aikaikkunaLoppu = 4;</code>
       */
      public boolean hasAikaikkunaLoppu() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 aikaikkunaLoppu = 4;</code>
       */
      public long getAikaikkunaLoppu() {
        return aikaikkunaLoppu_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasLaskennallinenAnturiId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasArvo()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt64(1, laskennallinenAnturiId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, arvo_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt64(3, aikaikkunaAlku_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt64(4, aikaikkunaLoppu_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, laskennallinenAnturiId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, arvo_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, aikaikkunaAlku_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(4, aikaikkunaLoppu_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Anturi)) {
          return super.equals(obj);
        }
        Anturi other = (Anturi) obj;

        boolean result = true;
        result = result && (hasLaskennallinenAnturiId() == other.hasLaskennallinenAnturiId());
        if (hasLaskennallinenAnturiId()) {
          result = result && (getLaskennallinenAnturiId()
              == other.getLaskennallinenAnturiId());
        }
        result = result && (hasArvo() == other.hasArvo());
        if (hasArvo()) {
          result = result && (getArvo()
              == other.getArvo());
        }
        result = result && (hasAikaikkunaAlku() == other.hasAikaikkunaAlku());
        if (hasAikaikkunaAlku()) {
          result = result && (getAikaikkunaAlku()
              == other.getAikaikkunaAlku());
        }
        result = result && (hasAikaikkunaLoppu() == other.hasAikaikkunaLoppu());
        if (hasAikaikkunaLoppu()) {
          result = result && (getAikaikkunaLoppu()
              == other.getAikaikkunaLoppu());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasLaskennallinenAnturiId()) {
          hash = (37 * hash) + LASKENNALLINENANTURIID_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getLaskennallinenAnturiId());
        }
        if (hasArvo()) {
          hash = (37 * hash) + ARVO_FIELD_NUMBER;
          hash = (53 * hash) + getArvo();
        }
        if (hasAikaikkunaAlku()) {
          hash = (37 * hash) + AIKAIKKUNAALKU_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getAikaikkunaAlku());
        }
        if (hasAikaikkunaLoppu()) {
          hash = (37 * hash) + AIKAIKKUNALOPPU_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getAikaikkunaLoppu());
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Anturi parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Anturi parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Anturi parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Anturi parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Anturi parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Anturi parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Anturi parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Anturi parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Anturi parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Anturi parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Anturi parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Anturi parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Anturi prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code lam.Lam.Anturi}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:lam.Lam.Anturi)
          AnturiOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return LAMRealtimeProtos.internal_static_lam_Lam_Anturi_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return LAMRealtimeProtos.internal_static_lam_Lam_Anturi_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Anturi.class, Builder.class);
        }

        // Construct using fi.ely.lotju.lam.proto.LAMRealtimeProtos.Lam.Anturi.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          laskennallinenAnturiId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          arvo_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          aikaikkunaAlku_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000004);
          aikaikkunaLoppu_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return LAMRealtimeProtos.internal_static_lam_Lam_Anturi_descriptor;
        }

        public Anturi getDefaultInstanceForType() {
          return Anturi.getDefaultInstance();
        }

        public Anturi build() {
          Anturi result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Anturi buildPartial() {
          Anturi result = new Anturi(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.laskennallinenAnturiId_ = laskennallinenAnturiId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.arvo_ = arvo_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.aikaikkunaAlku_ = aikaikkunaAlku_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.aikaikkunaLoppu_ = aikaikkunaLoppu_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Anturi) {
            return mergeFrom((Anturi)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Anturi other) {
          if (other == Anturi.getDefaultInstance()) return this;
          if (other.hasLaskennallinenAnturiId()) {
            setLaskennallinenAnturiId(other.getLaskennallinenAnturiId());
          }
          if (other.hasArvo()) {
            setArvo(other.getArvo());
          }
          if (other.hasAikaikkunaAlku()) {
            setAikaikkunaAlku(other.getAikaikkunaAlku());
          }
          if (other.hasAikaikkunaLoppu()) {
            setAikaikkunaLoppu(other.getAikaikkunaLoppu());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasLaskennallinenAnturiId()) {
            return false;
          }
          if (!hasArvo()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Anturi parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Anturi) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private long laskennallinenAnturiId_ ;
        /**
         * <code>required int64 laskennallinenAnturiId = 1;</code>
         */
        public boolean hasLaskennallinenAnturiId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int64 laskennallinenAnturiId = 1;</code>
         */
        public long getLaskennallinenAnturiId() {
          return laskennallinenAnturiId_;
        }
        /**
         * <code>required int64 laskennallinenAnturiId = 1;</code>
         */
        public Builder setLaskennallinenAnturiId(long value) {
          bitField0_ |= 0x00000001;
          laskennallinenAnturiId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 laskennallinenAnturiId = 1;</code>
         */
        public Builder clearLaskennallinenAnturiId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          laskennallinenAnturiId_ = 0L;
          onChanged();
          return this;
        }

        private int arvo_ ;
        /**
         * <code>required int32 arvo = 2;</code>
         */
        public boolean hasArvo() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 arvo = 2;</code>
         */
        public int getArvo() {
          return arvo_;
        }
        /**
         * <code>required int32 arvo = 2;</code>
         */
        public Builder setArvo(int value) {
          bitField0_ |= 0x00000002;
          arvo_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 arvo = 2;</code>
         */
        public Builder clearArvo() {
          bitField0_ = (bitField0_ & ~0x00000002);
          arvo_ = 0;
          onChanged();
          return this;
        }

        private long aikaikkunaAlku_ ;
        /**
         * <code>optional int64 aikaikkunaAlku = 3;</code>
         */
        public boolean hasAikaikkunaAlku() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int64 aikaikkunaAlku = 3;</code>
         */
        public long getAikaikkunaAlku() {
          return aikaikkunaAlku_;
        }
        /**
         * <code>optional int64 aikaikkunaAlku = 3;</code>
         */
        public Builder setAikaikkunaAlku(long value) {
          bitField0_ |= 0x00000004;
          aikaikkunaAlku_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 aikaikkunaAlku = 3;</code>
         */
        public Builder clearAikaikkunaAlku() {
          bitField0_ = (bitField0_ & ~0x00000004);
          aikaikkunaAlku_ = 0L;
          onChanged();
          return this;
        }

        private long aikaikkunaLoppu_ ;
        /**
         * <code>optional int64 aikaikkunaLoppu = 4;</code>
         */
        public boolean hasAikaikkunaLoppu() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional int64 aikaikkunaLoppu = 4;</code>
         */
        public long getAikaikkunaLoppu() {
          return aikaikkunaLoppu_;
        }
        /**
         * <code>optional int64 aikaikkunaLoppu = 4;</code>
         */
        public Builder setAikaikkunaLoppu(long value) {
          bitField0_ |= 0x00000008;
          aikaikkunaLoppu_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 aikaikkunaLoppu = 4;</code>
         */
        public Builder clearAikaikkunaLoppu() {
          bitField0_ = (bitField0_ & ~0x00000008);
          aikaikkunaLoppu_ = 0L;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:lam.Lam.Anturi)
      }

      // @@protoc_insertion_point(class_scope:lam.Lam.Anturi)
      private static final Anturi DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Anturi();
      }

      public static Anturi getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @Deprecated public static final com.google.protobuf.Parser<Anturi>
          PARSER = new com.google.protobuf.AbstractParser<Anturi>() {
        public Anturi parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Anturi(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Anturi> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Anturi> getParserForType() {
        return PARSER;
      }

      public Anturi getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ASEMAID_FIELD_NUMBER = 1;
    private long asemaId_;
    /**
     * <code>required int64 asemaId = 1;</code>
     */
    public boolean hasAsemaId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 asemaId = 1;</code>
     */
    public long getAsemaId() {
      return asemaId_;
    }

    public static final int AIKA_FIELD_NUMBER = 2;
    private long aika_;
    /**
     * <code>required int64 aika = 2;</code>
     */
    public boolean hasAika() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 aika = 2;</code>
     */
    public long getAika() {
      return aika_;
    }

    public static final int ISREALTIME_FIELD_NUMBER = 3;
    private boolean isRealtime_;
    /**
     * <code>required bool isRealtime = 3 [default = true];</code>
     */
    public boolean hasIsRealtime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool isRealtime = 3 [default = true];</code>
     */
    public boolean getIsRealtime() {
      return isRealtime_;
    }

    public static final int ISNOLLAOHITUS_FIELD_NUMBER = 4;
    private boolean isNollaOhitus_;
    /**
     * <code>required bool isNollaOhitus = 4 [default = false];</code>
     */
    public boolean hasIsNollaOhitus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool isNollaOhitus = 4 [default = false];</code>
     */
    public boolean getIsNollaOhitus() {
      return isNollaOhitus_;
    }

    public static final int ANTURI_FIELD_NUMBER = 5;
    private java.util.List<Anturi> anturi_;
    /**
     * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
     */
    public java.util.List<Anturi> getAnturiList() {
      return anturi_;
    }
    /**
     * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
     */
    public java.util.List<? extends AnturiOrBuilder>
        getAnturiOrBuilderList() {
      return anturi_;
    }
    /**
     * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
     */
    public int getAnturiCount() {
      return anturi_.size();
    }
    /**
     * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
     */
    public Anturi getAnturi(int index) {
      return anturi_.get(index);
    }
    /**
     * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
     */
    public AnturiOrBuilder getAnturiOrBuilder(
        int index) {
      return anturi_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAsemaId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAika()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsRealtime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsNollaOhitus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAnturiCount(); i++) {
        if (!getAnturi(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, asemaId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, aika_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, isRealtime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, isNollaOhitus_);
      }
      for (int i = 0; i < anturi_.size(); i++) {
        output.writeMessage(5, anturi_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, asemaId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, aika_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isRealtime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isNollaOhitus_);
      }
      for (int i = 0; i < anturi_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, anturi_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Lam)) {
        return super.equals(obj);
      }
      Lam other = (Lam) obj;

      boolean result = true;
      result = result && (hasAsemaId() == other.hasAsemaId());
      if (hasAsemaId()) {
        result = result && (getAsemaId()
            == other.getAsemaId());
      }
      result = result && (hasAika() == other.hasAika());
      if (hasAika()) {
        result = result && (getAika()
            == other.getAika());
      }
      result = result && (hasIsRealtime() == other.hasIsRealtime());
      if (hasIsRealtime()) {
        result = result && (getIsRealtime()
            == other.getIsRealtime());
      }
      result = result && (hasIsNollaOhitus() == other.hasIsNollaOhitus());
      if (hasIsNollaOhitus()) {
        result = result && (getIsNollaOhitus()
            == other.getIsNollaOhitus());
      }
      result = result && getAnturiList()
          .equals(other.getAnturiList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAsemaId()) {
        hash = (37 * hash) + ASEMAID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAsemaId());
      }
      if (hasAika()) {
        hash = (37 * hash) + AIKA_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAika());
      }
      if (hasIsRealtime()) {
        hash = (37 * hash) + ISREALTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsRealtime());
      }
      if (hasIsNollaOhitus()) {
        hash = (37 * hash) + ISNOLLAOHITUS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsNollaOhitus());
      }
      if (getAnturiCount() > 0) {
        hash = (37 * hash) + ANTURI_FIELD_NUMBER;
        hash = (53 * hash) + getAnturiList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Lam parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lam parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Lam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Lam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Lam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Lam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Lam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Lam prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lam.Lam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lam.Lam)
        LamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LAMRealtimeProtos.internal_static_lam_Lam_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LAMRealtimeProtos.internal_static_lam_Lam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Lam.class, Builder.class);
      }

      // Construct using fi.ely.lotju.lam.proto.LAMRealtimeProtos.Lam.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAnturiFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        asemaId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        aika_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        isRealtime_ = true;
        bitField0_ = (bitField0_ & ~0x00000004);
        isNollaOhitus_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (anturiBuilder_ == null) {
          anturi_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          anturiBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LAMRealtimeProtos.internal_static_lam_Lam_descriptor;
      }

      public Lam getDefaultInstanceForType() {
        return Lam.getDefaultInstance();
      }

      public Lam build() {
        Lam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Lam buildPartial() {
        Lam result = new Lam(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.asemaId_ = asemaId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.aika_ = aika_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isRealtime_ = isRealtime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isNollaOhitus_ = isNollaOhitus_;
        if (anturiBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            anturi_ = java.util.Collections.unmodifiableList(anturi_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.anturi_ = anturi_;
        } else {
          result.anturi_ = anturiBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Lam) {
          return mergeFrom((Lam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Lam other) {
        if (other == Lam.getDefaultInstance()) return this;
        if (other.hasAsemaId()) {
          setAsemaId(other.getAsemaId());
        }
        if (other.hasAika()) {
          setAika(other.getAika());
        }
        if (other.hasIsRealtime()) {
          setIsRealtime(other.getIsRealtime());
        }
        if (other.hasIsNollaOhitus()) {
          setIsNollaOhitus(other.getIsNollaOhitus());
        }
        if (anturiBuilder_ == null) {
          if (!other.anturi_.isEmpty()) {
            if (anturi_.isEmpty()) {
              anturi_ = other.anturi_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureAnturiIsMutable();
              anturi_.addAll(other.anturi_);
            }
            onChanged();
          }
        } else {
          if (!other.anturi_.isEmpty()) {
            if (anturiBuilder_.isEmpty()) {
              anturiBuilder_.dispose();
              anturiBuilder_ = null;
              anturi_ = other.anturi_;
              bitField0_ = (bitField0_ & ~0x00000010);
              anturiBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAnturiFieldBuilder() : null;
            } else {
              anturiBuilder_.addAllMessages(other.anturi_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAsemaId()) {
          return false;
        }
        if (!hasAika()) {
          return false;
        }
        if (!hasIsRealtime()) {
          return false;
        }
        if (!hasIsNollaOhitus()) {
          return false;
        }
        for (int i = 0; i < getAnturiCount(); i++) {
          if (!getAnturi(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Lam parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Lam) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long asemaId_ ;
      /**
       * <code>required int64 asemaId = 1;</code>
       */
      public boolean hasAsemaId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 asemaId = 1;</code>
       */
      public long getAsemaId() {
        return asemaId_;
      }
      /**
       * <code>required int64 asemaId = 1;</code>
       */
      public Builder setAsemaId(long value) {
        bitField0_ |= 0x00000001;
        asemaId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 asemaId = 1;</code>
       */
      public Builder clearAsemaId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        asemaId_ = 0L;
        onChanged();
        return this;
      }

      private long aika_ ;
      /**
       * <code>required int64 aika = 2;</code>
       */
      public boolean hasAika() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 aika = 2;</code>
       */
      public long getAika() {
        return aika_;
      }
      /**
       * <code>required int64 aika = 2;</code>
       */
      public Builder setAika(long value) {
        bitField0_ |= 0x00000002;
        aika_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 aika = 2;</code>
       */
      public Builder clearAika() {
        bitField0_ = (bitField0_ & ~0x00000002);
        aika_ = 0L;
        onChanged();
        return this;
      }

      private boolean isRealtime_ = true;
      /**
       * <code>required bool isRealtime = 3 [default = true];</code>
       */
      public boolean hasIsRealtime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool isRealtime = 3 [default = true];</code>
       */
      public boolean getIsRealtime() {
        return isRealtime_;
      }
      /**
       * <code>required bool isRealtime = 3 [default = true];</code>
       */
      public Builder setIsRealtime(boolean value) {
        bitField0_ |= 0x00000004;
        isRealtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isRealtime = 3 [default = true];</code>
       */
      public Builder clearIsRealtime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isRealtime_ = true;
        onChanged();
        return this;
      }

      private boolean isNollaOhitus_ ;
      /**
       * <code>required bool isNollaOhitus = 4 [default = false];</code>
       */
      public boolean hasIsNollaOhitus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool isNollaOhitus = 4 [default = false];</code>
       */
      public boolean getIsNollaOhitus() {
        return isNollaOhitus_;
      }
      /**
       * <code>required bool isNollaOhitus = 4 [default = false];</code>
       */
      public Builder setIsNollaOhitus(boolean value) {
        bitField0_ |= 0x00000008;
        isNollaOhitus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isNollaOhitus = 4 [default = false];</code>
       */
      public Builder clearIsNollaOhitus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isNollaOhitus_ = false;
        onChanged();
        return this;
      }

      private java.util.List<Anturi> anturi_ =
        java.util.Collections.emptyList();
      private void ensureAnturiIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          anturi_ = new java.util.ArrayList<Anturi>(anturi_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Anturi, Anturi.Builder, AnturiOrBuilder> anturiBuilder_;

      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public java.util.List<Anturi> getAnturiList() {
        if (anturiBuilder_ == null) {
          return java.util.Collections.unmodifiableList(anturi_);
        } else {
          return anturiBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public int getAnturiCount() {
        if (anturiBuilder_ == null) {
          return anturi_.size();
        } else {
          return anturiBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public Anturi getAnturi(int index) {
        if (anturiBuilder_ == null) {
          return anturi_.get(index);
        } else {
          return anturiBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public Builder setAnturi(
          int index, Anturi value) {
        if (anturiBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnturiIsMutable();
          anturi_.set(index, value);
          onChanged();
        } else {
          anturiBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public Builder setAnturi(
          int index, Anturi.Builder builderForValue) {
        if (anturiBuilder_ == null) {
          ensureAnturiIsMutable();
          anturi_.set(index, builderForValue.build());
          onChanged();
        } else {
          anturiBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public Builder addAnturi(Anturi value) {
        if (anturiBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnturiIsMutable();
          anturi_.add(value);
          onChanged();
        } else {
          anturiBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public Builder addAnturi(
          int index, Anturi value) {
        if (anturiBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnturiIsMutable();
          anturi_.add(index, value);
          onChanged();
        } else {
          anturiBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public Builder addAnturi(
          Anturi.Builder builderForValue) {
        if (anturiBuilder_ == null) {
          ensureAnturiIsMutable();
          anturi_.add(builderForValue.build());
          onChanged();
        } else {
          anturiBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public Builder addAnturi(
          int index, Anturi.Builder builderForValue) {
        if (anturiBuilder_ == null) {
          ensureAnturiIsMutable();
          anturi_.add(index, builderForValue.build());
          onChanged();
        } else {
          anturiBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public Builder addAllAnturi(
          Iterable<? extends Anturi> values) {
        if (anturiBuilder_ == null) {
          ensureAnturiIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, anturi_);
          onChanged();
        } else {
          anturiBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public Builder clearAnturi() {
        if (anturiBuilder_ == null) {
          anturi_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          anturiBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public Builder removeAnturi(int index) {
        if (anturiBuilder_ == null) {
          ensureAnturiIsMutable();
          anturi_.remove(index);
          onChanged();
        } else {
          anturiBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public Anturi.Builder getAnturiBuilder(
          int index) {
        return getAnturiFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public AnturiOrBuilder getAnturiOrBuilder(
          int index) {
        if (anturiBuilder_ == null) {
          return anturi_.get(index);  } else {
          return anturiBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public java.util.List<? extends AnturiOrBuilder>
           getAnturiOrBuilderList() {
        if (anturiBuilder_ != null) {
          return anturiBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(anturi_);
        }
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public Anturi.Builder addAnturiBuilder() {
        return getAnturiFieldBuilder().addBuilder(
            Anturi.getDefaultInstance());
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public Anturi.Builder addAnturiBuilder(
          int index) {
        return getAnturiFieldBuilder().addBuilder(
            index, Anturi.getDefaultInstance());
      }
      /**
       * <code>repeated .lam.Lam.Anturi anturi = 5;</code>
       */
      public java.util.List<Anturi.Builder>
           getAnturiBuilderList() {
        return getAnturiFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Anturi, Anturi.Builder, AnturiOrBuilder>
          getAnturiFieldBuilder() {
        if (anturiBuilder_ == null) {
          anturiBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Anturi, Anturi.Builder, AnturiOrBuilder>(
                  anturi_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          anturi_ = null;
        }
        return anturiBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lam.Lam)
    }

    // @@protoc_insertion_point(class_scope:lam.Lam)
    private static final Lam DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Lam();
    }

    public static Lam getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Lam>
        PARSER = new com.google.protobuf.AbstractParser<Lam>() {
      public Lam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Lam(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Lam> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Lam> getParserForType() {
      return PARSER;
    }

    public Lam getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lam_Lam_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lam_Lam_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lam_Lam_Anturi_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lam_Lam_Anturi_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022lam_realtime.proto\022\003lam\"\346\001\n\003Lam\022\017\n\007ase" +
      "maId\030\001 \002(\003\022\014\n\004aika\030\002 \002(\003\022\030\n\nisRealtime\030\003" +
      " \002(\010:\004true\022\034\n\risNollaOhitus\030\004 \002(\010:\005false" +
      "\022\037\n\006anturi\030\005 \003(\0132\017.lam.Lam.Anturi\032g\n\006Ant" +
      "uri\022\036\n\026laskennallinenAnturiId\030\001 \002(\003\022\014\n\004a" +
      "rvo\030\002 \002(\005\022\026\n\016aikaikkunaAlku\030\003 \001(\003\022\027\n\017aik" +
      "aikkunaLoppu\030\004 \001(\003B+\n\026fi.ely.lotju.lam.p" +
      "rotoB\021LAMRealtimeProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lam_Lam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lam_Lam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lam_Lam_descriptor,
        new String[] { "AsemaId", "Aika", "IsRealtime", "IsNollaOhitus", "Anturi", });
    internal_static_lam_Lam_Anturi_descriptor =
      internal_static_lam_Lam_descriptor.getNestedTypes().get(0);
    internal_static_lam_Lam_Anturi_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lam_Lam_Anturi_descriptor,
        new String[] { "LaskennallinenAnturiId", "Arvo", "AikaikkunaAlku", "AikaikkunaLoppu", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
