// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kuva.proto

package fi.ely.lotju.kamera.proto;

public final class KuvaProtos {
    private KuvaProtos() {}
    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface KuvaOrBuilder extends
        // @@protoc_insertion_point(interface_extends:kamera.Kuva)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int64 kamera_id = 1;</code>
         */
        boolean hasKameraId();
        /**
         * <code>required int64 kamera_id = 1;</code>
         */
        long getKameraId();

        /**
         * <code>required int64 esiasento_id = 2;</code>
         */
        boolean hasEsiasentoId();
        /**
         * <code>required int64 esiasento_id = 2;</code>
         */
        long getEsiasentoId();

        /**
         * <code>required int64 kuva_id = 3;</code>
         */
        boolean hasKuvaId();
        /**
         * <code>required int64 kuva_id = 3;</code>
         */
        long getKuvaId();

        /**
         * <code>required int64 aikaleima = 4;</code>
         */
        boolean hasAikaleima();
        /**
         * <code>required int64 aikaleima = 4;</code>
         */
        long getAikaleima();

        /**
         * <code>required string nimi = 5;</code>
         */
        boolean hasNimi();
        /**
         * <code>required string nimi = 5;</code>
         */
        java.lang.String getNimi();
        /**
         * <code>required string nimi = 5;</code>
         */
        com.google.protobuf.ByteString
        getNimiBytes();

        /**
         * <code>required string esiasennon_nimi = 6;</code>
         */
        boolean hasEsiasennonNimi();
        /**
         * <code>required string esiasennon_nimi = 6;</code>
         */
        java.lang.String getEsiasennonNimi();
        /**
         * <code>required string esiasennon_nimi = 6;</code>
         */
        com.google.protobuf.ByteString
        getEsiasennonNimiBytes();

        /**
         * <code>required bool julkinen = 7;</code>
         */
        boolean hasJulkinen();
        /**
         * <code>required bool julkinen = 7;</code>
         */
        boolean getJulkinen();

        /**
         * <code>required string aseman_nimi = 8;</code>
         */
        boolean hasAsemanNimi();
        /**
         * <code>required string aseman_nimi = 8;</code>
         */
        java.lang.String getAsemanNimi();
        /**
         * <code>required string aseman_nimi = 8;</code>
         */
        com.google.protobuf.ByteString
        getAsemanNimiBytes();

        /**
         * <code>optional string liviId = 9;</code>
         */
        boolean hasLiviId();
        /**
         * <code>optional string liviId = 9;</code>
         */
        java.lang.String getLiviId();
        /**
         * <code>optional string liviId = 9;</code>
         */
        com.google.protobuf.ByteString
        getLiviIdBytes();

        /**
         * <code>optional int32 tienumero = 10;</code>
         */
        boolean hasTienumero();
        /**
         * <code>optional int32 tienumero = 10;</code>
         */
        int getTienumero();

        /**
         * <code>optional int32 tieosa = 11;</code>
         */
        boolean hasTieosa();
        /**
         * <code>optional int32 tieosa = 11;</code>
         */
        int getTieosa();

        /**
         * <code>optional int32 etaisyys_tieosan_alusta = 12;</code>
         */
        boolean hasEtaisyysTieosanAlusta();
        /**
         * <code>optional int32 etaisyys_tieosan_alusta = 12;</code>
         */
        int getEtaisyysTieosanAlusta();

        /**
         * <code>optional int32 ajorata = 13;</code>
         */
        boolean hasAjorata();
        /**
         * <code>optional int32 ajorata = 13;</code>
         */
        int getAjorata();

        /**
         * <code>optional int32 puoli = 14;</code>
         */
        boolean hasPuoli();
        /**
         * <code>optional int32 puoli = 14;</code>
         */
        int getPuoli();

        /**
         * <code>optional string x_koordinaatti = 15;</code>
         */
        boolean hasXKoordinaatti();
        /**
         * <code>optional string x_koordinaatti = 15;</code>
         */
        java.lang.String getXKoordinaatti();
        /**
         * <code>optional string x_koordinaatti = 15;</code>
         */
        com.google.protobuf.ByteString
        getXKoordinaattiBytes();

        /**
         * <code>optional string y_koordinaatti = 16;</code>
         */
        boolean hasYKoordinaatti();
        /**
         * <code>optional string y_koordinaatti = 16;</code>
         */
        java.lang.String getYKoordinaatti();
        /**
         * <code>optional string y_koordinaatti = 16;</code>
         */
        com.google.protobuf.ByteString
        getYKoordinaattiBytes();

        /**
         * <code>optional string z_koordinaatti = 17;</code>
         */
        boolean hasZKoordinaatti();
        /**
         * <code>optional string z_koordinaatti = 17;</code>
         */
        java.lang.String getZKoordinaatti();
        /**
         * <code>optional string z_koordinaatti = 17;</code>
         */
        com.google.protobuf.ByteString
        getZKoordinaattiBytes();

        /**
         * <code>optional int64 ttl = 18;</code>
         */
        boolean hasTtl();
        /**
         * <code>optional int64 ttl = 18;</code>
         */
        long getTtl();
    }
    /**
     * Protobuf type {@code kamera.Kuva}
     */
    public  static final class Kuva extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:kamera.Kuva)
        KuvaOrBuilder {
        // Use Kuva.newBuilder() to construct.
        private Kuva(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Kuva() {
            kameraId_ = 0L;
            esiasentoId_ = 0L;
            kuvaId_ = 0L;
            aikaleima_ = 0L;
            nimi_ = "";
            esiasennonNimi_ = "";
            julkinen_ = false;
            asemanNimi_ = "";
            liviId_ = "";
            tienumero_ = 0;
            tieosa_ = 0;
            etaisyysTieosanAlusta_ = 0;
            ajorata_ = 0;
            puoli_ = 0;
            xKoordinaatti_ = "";
            yKoordinaatti_ = "";
            zKoordinaatti_ = "";
            ttl_ = 0L;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Kuva(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFields,
                            extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {
                        bitField0_ |= 0x00000001;
                        kameraId_ = input.readInt64();
                        break;
                    }
                    case 16: {
                        bitField0_ |= 0x00000002;
                        esiasentoId_ = input.readInt64();
                        break;
                    }
                    case 24: {
                        bitField0_ |= 0x00000004;
                        kuvaId_ = input.readInt64();
                        break;
                    }
                    case 32: {
                        bitField0_ |= 0x00000008;
                        aikaleima_ = input.readInt64();
                        break;
                    }
                    case 42: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000010;
                        nimi_ = bs;
                        break;
                    }
                    case 50: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000020;
                        esiasennonNimi_ = bs;
                        break;
                    }
                    case 56: {
                        bitField0_ |= 0x00000040;
                        julkinen_ = input.readBool();
                        break;
                    }
                    case 66: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000080;
                        asemanNimi_ = bs;
                        break;
                    }
                    case 74: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000100;
                        liviId_ = bs;
                        break;
                    }
                    case 80: {
                        bitField0_ |= 0x00000200;
                        tienumero_ = input.readInt32();
                        break;
                    }
                    case 88: {
                        bitField0_ |= 0x00000400;
                        tieosa_ = input.readInt32();
                        break;
                    }
                    case 96: {
                        bitField0_ |= 0x00000800;
                        etaisyysTieosanAlusta_ = input.readInt32();
                        break;
                    }
                    case 104: {
                        bitField0_ |= 0x00001000;
                        ajorata_ = input.readInt32();
                        break;
                    }
                    case 112: {
                        bitField0_ |= 0x00002000;
                        puoli_ = input.readInt32();
                        break;
                    }
                    case 122: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00004000;
                        xKoordinaatti_ = bs;
                        break;
                    }
                    case 130: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00008000;
                        yKoordinaatti_ = bs;
                        break;
                    }
                    case 138: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00010000;
                        zKoordinaatti_ = bs;
                        break;
                    }
                    case 144: {
                        bitField0_ |= 0x00020000;
                        ttl_ = input.readInt64();
                        break;
                    }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return fi.ely.lotju.kamera.proto.KuvaProtos.internal_static_kamera_Kuva_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return fi.ely.lotju.kamera.proto.KuvaProtos.internal_static_kamera_Kuva_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    fi.ely.lotju.kamera.proto.KuvaProtos.Kuva.class, fi.ely.lotju.kamera.proto.KuvaProtos.Kuva.Builder.class);
        }

        private int bitField0_;
        public static final int KAMERA_ID_FIELD_NUMBER = 1;
        private long kameraId_;
        /**
         * <code>required int64 kamera_id = 1;</code>
         */
        public boolean hasKameraId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int64 kamera_id = 1;</code>
         */
        public long getKameraId() {
            return kameraId_;
        }

        public static final int ESIASENTO_ID_FIELD_NUMBER = 2;
        private long esiasentoId_;
        /**
         * <code>required int64 esiasento_id = 2;</code>
         */
        public boolean hasEsiasentoId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int64 esiasento_id = 2;</code>
         */
        public long getEsiasentoId() {
            return esiasentoId_;
        }

        public static final int KUVA_ID_FIELD_NUMBER = 3;
        private long kuvaId_;
        /**
         * <code>required int64 kuva_id = 3;</code>
         */
        public boolean hasKuvaId() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required int64 kuva_id = 3;</code>
         */
        public long getKuvaId() {
            return kuvaId_;
        }

        public static final int AIKALEIMA_FIELD_NUMBER = 4;
        private long aikaleima_;
        /**
         * <code>required int64 aikaleima = 4;</code>
         */
        public boolean hasAikaleima() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required int64 aikaleima = 4;</code>
         */
        public long getAikaleima() {
            return aikaleima_;
        }

        public static final int NIMI_FIELD_NUMBER = 5;
        private volatile java.lang.Object nimi_;
        /**
         * <code>required string nimi = 5;</code>
         */
        public boolean hasNimi() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>required string nimi = 5;</code>
         */
        public java.lang.String getNimi() {
            java.lang.Object ref = nimi_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    nimi_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string nimi = 5;</code>
         */
        public com.google.protobuf.ByteString
        getNimiBytes() {
            java.lang.Object ref = nimi_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                nimi_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ESIASENNON_NIMI_FIELD_NUMBER = 6;
        private volatile java.lang.Object esiasennonNimi_;
        /**
         * <code>required string esiasennon_nimi = 6;</code>
         */
        public boolean hasEsiasennonNimi() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>required string esiasennon_nimi = 6;</code>
         */
        public java.lang.String getEsiasennonNimi() {
            java.lang.Object ref = esiasennonNimi_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    esiasennonNimi_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string esiasennon_nimi = 6;</code>
         */
        public com.google.protobuf.ByteString
        getEsiasennonNimiBytes() {
            java.lang.Object ref = esiasennonNimi_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                esiasennonNimi_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int JULKINEN_FIELD_NUMBER = 7;
        private boolean julkinen_;
        /**
         * <code>required bool julkinen = 7;</code>
         */
        public boolean hasJulkinen() {
            return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>required bool julkinen = 7;</code>
         */
        public boolean getJulkinen() {
            return julkinen_;
        }

        public static final int ASEMAN_NIMI_FIELD_NUMBER = 8;
        private volatile java.lang.Object asemanNimi_;
        /**
         * <code>required string aseman_nimi = 8;</code>
         */
        public boolean hasAsemanNimi() {
            return ((bitField0_ & 0x00000080) == 0x00000080);
        }
        /**
         * <code>required string aseman_nimi = 8;</code>
         */
        public java.lang.String getAsemanNimi() {
            java.lang.Object ref = asemanNimi_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    asemanNimi_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string aseman_nimi = 8;</code>
         */
        public com.google.protobuf.ByteString
        getAsemanNimiBytes() {
            java.lang.Object ref = asemanNimi_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                asemanNimi_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int LIVIID_FIELD_NUMBER = 9;
        private volatile java.lang.Object liviId_;
        /**
         * <code>optional string liviId = 9;</code>
         */
        public boolean hasLiviId() {
            return ((bitField0_ & 0x00000100) == 0x00000100);
        }
        /**
         * <code>optional string liviId = 9;</code>
         */
        public java.lang.String getLiviId() {
            java.lang.Object ref = liviId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    liviId_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string liviId = 9;</code>
         */
        public com.google.protobuf.ByteString
        getLiviIdBytes() {
            java.lang.Object ref = liviId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                liviId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TIENUMERO_FIELD_NUMBER = 10;
        private int tienumero_;
        /**
         * <code>optional int32 tienumero = 10;</code>
         */
        public boolean hasTienumero() {
            return ((bitField0_ & 0x00000200) == 0x00000200);
        }
        /**
         * <code>optional int32 tienumero = 10;</code>
         */
        public int getTienumero() {
            return tienumero_;
        }

        public static final int TIEOSA_FIELD_NUMBER = 11;
        private int tieosa_;
        /**
         * <code>optional int32 tieosa = 11;</code>
         */
        public boolean hasTieosa() {
            return ((bitField0_ & 0x00000400) == 0x00000400);
        }
        /**
         * <code>optional int32 tieosa = 11;</code>
         */
        public int getTieosa() {
            return tieosa_;
        }

        public static final int ETAISYYS_TIEOSAN_ALUSTA_FIELD_NUMBER = 12;
        private int etaisyysTieosanAlusta_;
        /**
         * <code>optional int32 etaisyys_tieosan_alusta = 12;</code>
         */
        public boolean hasEtaisyysTieosanAlusta() {
            return ((bitField0_ & 0x00000800) == 0x00000800);
        }
        /**
         * <code>optional int32 etaisyys_tieosan_alusta = 12;</code>
         */
        public int getEtaisyysTieosanAlusta() {
            return etaisyysTieosanAlusta_;
        }

        public static final int AJORATA_FIELD_NUMBER = 13;
        private int ajorata_;
        /**
         * <code>optional int32 ajorata = 13;</code>
         */
        public boolean hasAjorata() {
            return ((bitField0_ & 0x00001000) == 0x00001000);
        }
        /**
         * <code>optional int32 ajorata = 13;</code>
         */
        public int getAjorata() {
            return ajorata_;
        }

        public static final int PUOLI_FIELD_NUMBER = 14;
        private int puoli_;
        /**
         * <code>optional int32 puoli = 14;</code>
         */
        public boolean hasPuoli() {
            return ((bitField0_ & 0x00002000) == 0x00002000);
        }
        /**
         * <code>optional int32 puoli = 14;</code>
         */
        public int getPuoli() {
            return puoli_;
        }

        public static final int X_KOORDINAATTI_FIELD_NUMBER = 15;
        private volatile java.lang.Object xKoordinaatti_;
        /**
         * <code>optional string x_koordinaatti = 15;</code>
         */
        public boolean hasXKoordinaatti() {
            return ((bitField0_ & 0x00004000) == 0x00004000);
        }
        /**
         * <code>optional string x_koordinaatti = 15;</code>
         */
        public java.lang.String getXKoordinaatti() {
            java.lang.Object ref = xKoordinaatti_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    xKoordinaatti_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string x_koordinaatti = 15;</code>
         */
        public com.google.protobuf.ByteString
        getXKoordinaattiBytes() {
            java.lang.Object ref = xKoordinaatti_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                xKoordinaatti_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int Y_KOORDINAATTI_FIELD_NUMBER = 16;
        private volatile java.lang.Object yKoordinaatti_;
        /**
         * <code>optional string y_koordinaatti = 16;</code>
         */
        public boolean hasYKoordinaatti() {
            return ((bitField0_ & 0x00008000) == 0x00008000);
        }
        /**
         * <code>optional string y_koordinaatti = 16;</code>
         */
        public java.lang.String getYKoordinaatti() {
            java.lang.Object ref = yKoordinaatti_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    yKoordinaatti_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string y_koordinaatti = 16;</code>
         */
        public com.google.protobuf.ByteString
        getYKoordinaattiBytes() {
            java.lang.Object ref = yKoordinaatti_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                yKoordinaatti_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int Z_KOORDINAATTI_FIELD_NUMBER = 17;
        private volatile java.lang.Object zKoordinaatti_;
        /**
         * <code>optional string z_koordinaatti = 17;</code>
         */
        public boolean hasZKoordinaatti() {
            return ((bitField0_ & 0x00010000) == 0x00010000);
        }
        /**
         * <code>optional string z_koordinaatti = 17;</code>
         */
        public java.lang.String getZKoordinaatti() {
            java.lang.Object ref = zKoordinaatti_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    zKoordinaatti_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string z_koordinaatti = 17;</code>
         */
        public com.google.protobuf.ByteString
        getZKoordinaattiBytes() {
            java.lang.Object ref = zKoordinaatti_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                zKoordinaatti_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TTL_FIELD_NUMBER = 18;
        private long ttl_;
        /**
         * <code>optional int64 ttl = 18;</code>
         */
        public boolean hasTtl() {
            return ((bitField0_ & 0x00020000) == 0x00020000);
        }
        /**
         * <code>optional int64 ttl = 18;</code>
         */
        public long getTtl() {
            return ttl_;
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasKameraId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasEsiasentoId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasKuvaId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasAikaleima()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasNimi()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasEsiasennonNimi()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasJulkinen()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasAsemanNimi()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt64(1, kameraId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt64(2, esiasentoId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt64(3, kuvaId_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeInt64(4, aikaleima_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, nimi_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, esiasennonNimi_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                output.writeBool(7, julkinen_);
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 8, asemanNimi_);
            }
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 9, liviId_);
            }
            if (((bitField0_ & 0x00000200) == 0x00000200)) {
                output.writeInt32(10, tienumero_);
            }
            if (((bitField0_ & 0x00000400) == 0x00000400)) {
                output.writeInt32(11, tieosa_);
            }
            if (((bitField0_ & 0x00000800) == 0x00000800)) {
                output.writeInt32(12, etaisyysTieosanAlusta_);
            }
            if (((bitField0_ & 0x00001000) == 0x00001000)) {
                output.writeInt32(13, ajorata_);
            }
            if (((bitField0_ & 0x00002000) == 0x00002000)) {
                output.writeInt32(14, puoli_);
            }
            if (((bitField0_ & 0x00004000) == 0x00004000)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 15, xKoordinaatti_);
            }
            if (((bitField0_ & 0x00008000) == 0x00008000)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 16, yKoordinaatti_);
            }
            if (((bitField0_ & 0x00010000) == 0x00010000)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 17, zKoordinaatti_);
            }
            if (((bitField0_ & 0x00020000) == 0x00020000)) {
                output.writeInt64(18, ttl_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(1, kameraId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(2, esiasentoId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(3, kuvaId_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(4, aikaleima_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, nimi_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, esiasennonNimi_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                size += com.google.protobuf.CodedOutputStream
                    .computeBoolSize(7, julkinen_);
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, asemanNimi_);
            }
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, liviId_);
            }
            if (((bitField0_ & 0x00000200) == 0x00000200)) {
                size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(10, tienumero_);
            }
            if (((bitField0_ & 0x00000400) == 0x00000400)) {
                size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(11, tieosa_);
            }
            if (((bitField0_ & 0x00000800) == 0x00000800)) {
                size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(12, etaisyysTieosanAlusta_);
            }
            if (((bitField0_ & 0x00001000) == 0x00001000)) {
                size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(13, ajorata_);
            }
            if (((bitField0_ & 0x00002000) == 0x00002000)) {
                size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(14, puoli_);
            }
            if (((bitField0_ & 0x00004000) == 0x00004000)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, xKoordinaatti_);
            }
            if (((bitField0_ & 0x00008000) == 0x00008000)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, yKoordinaatti_);
            }
            if (((bitField0_ & 0x00010000) == 0x00010000)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, zKoordinaatti_);
            }
            if (((bitField0_ & 0x00020000) == 0x00020000)) {
                size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(18, ttl_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof fi.ely.lotju.kamera.proto.KuvaProtos.Kuva)) {
                return super.equals(obj);
            }
            fi.ely.lotju.kamera.proto.KuvaProtos.Kuva other = (fi.ely.lotju.kamera.proto.KuvaProtos.Kuva) obj;

            boolean result = true;
            result = result && (hasKameraId() == other.hasKameraId());
            if (hasKameraId()) {
                result = result && (getKameraId()
                    == other.getKameraId());
            }
            result = result && (hasEsiasentoId() == other.hasEsiasentoId());
            if (hasEsiasentoId()) {
                result = result && (getEsiasentoId()
                    == other.getEsiasentoId());
            }
            result = result && (hasKuvaId() == other.hasKuvaId());
            if (hasKuvaId()) {
                result = result && (getKuvaId()
                    == other.getKuvaId());
            }
            result = result && (hasAikaleima() == other.hasAikaleima());
            if (hasAikaleima()) {
                result = result && (getAikaleima()
                    == other.getAikaleima());
            }
            result = result && (hasNimi() == other.hasNimi());
            if (hasNimi()) {
                result = result && getNimi()
                    .equals(other.getNimi());
            }
            result = result && (hasEsiasennonNimi() == other.hasEsiasennonNimi());
            if (hasEsiasennonNimi()) {
                result = result && getEsiasennonNimi()
                    .equals(other.getEsiasennonNimi());
            }
            result = result && (hasJulkinen() == other.hasJulkinen());
            if (hasJulkinen()) {
                result = result && (getJulkinen()
                    == other.getJulkinen());
            }
            result = result && (hasAsemanNimi() == other.hasAsemanNimi());
            if (hasAsemanNimi()) {
                result = result && getAsemanNimi()
                    .equals(other.getAsemanNimi());
            }
            result = result && (hasLiviId() == other.hasLiviId());
            if (hasLiviId()) {
                result = result && getLiviId()
                    .equals(other.getLiviId());
            }
            result = result && (hasTienumero() == other.hasTienumero());
            if (hasTienumero()) {
                result = result && (getTienumero()
                    == other.getTienumero());
            }
            result = result && (hasTieosa() == other.hasTieosa());
            if (hasTieosa()) {
                result = result && (getTieosa()
                    == other.getTieosa());
            }
            result = result && (hasEtaisyysTieosanAlusta() == other.hasEtaisyysTieosanAlusta());
            if (hasEtaisyysTieosanAlusta()) {
                result = result && (getEtaisyysTieosanAlusta()
                    == other.getEtaisyysTieosanAlusta());
            }
            result = result && (hasAjorata() == other.hasAjorata());
            if (hasAjorata()) {
                result = result && (getAjorata()
                    == other.getAjorata());
            }
            result = result && (hasPuoli() == other.hasPuoli());
            if (hasPuoli()) {
                result = result && (getPuoli()
                    == other.getPuoli());
            }
            result = result && (hasXKoordinaatti() == other.hasXKoordinaatti());
            if (hasXKoordinaatti()) {
                result = result && getXKoordinaatti()
                    .equals(other.getXKoordinaatti());
            }
            result = result && (hasYKoordinaatti() == other.hasYKoordinaatti());
            if (hasYKoordinaatti()) {
                result = result && getYKoordinaatti()
                    .equals(other.getYKoordinaatti());
            }
            result = result && (hasZKoordinaatti() == other.hasZKoordinaatti());
            if (hasZKoordinaatti()) {
                result = result && getZKoordinaatti()
                    .equals(other.getZKoordinaatti());
            }
            result = result && (hasTtl() == other.hasTtl());
            if (hasTtl()) {
                result = result && (getTtl()
                    == other.getTtl());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            if (hasKameraId()) {
                hash = (37 * hash) + KAMERA_ID_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getKameraId());
            }
            if (hasEsiasentoId()) {
                hash = (37 * hash) + ESIASENTO_ID_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getEsiasentoId());
            }
            if (hasKuvaId()) {
                hash = (37 * hash) + KUVA_ID_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getKuvaId());
            }
            if (hasAikaleima()) {
                hash = (37 * hash) + AIKALEIMA_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getAikaleima());
            }
            if (hasNimi()) {
                hash = (37 * hash) + NIMI_FIELD_NUMBER;
                hash = (53 * hash) + getNimi().hashCode();
            }
            if (hasEsiasennonNimi()) {
                hash = (37 * hash) + ESIASENNON_NIMI_FIELD_NUMBER;
                hash = (53 * hash) + getEsiasennonNimi().hashCode();
            }
            if (hasJulkinen()) {
                hash = (37 * hash) + JULKINEN_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getJulkinen());
            }
            if (hasAsemanNimi()) {
                hash = (37 * hash) + ASEMAN_NIMI_FIELD_NUMBER;
                hash = (53 * hash) + getAsemanNimi().hashCode();
            }
            if (hasLiviId()) {
                hash = (37 * hash) + LIVIID_FIELD_NUMBER;
                hash = (53 * hash) + getLiviId().hashCode();
            }
            if (hasTienumero()) {
                hash = (37 * hash) + TIENUMERO_FIELD_NUMBER;
                hash = (53 * hash) + getTienumero();
            }
            if (hasTieosa()) {
                hash = (37 * hash) + TIEOSA_FIELD_NUMBER;
                hash = (53 * hash) + getTieosa();
            }
            if (hasEtaisyysTieosanAlusta()) {
                hash = (37 * hash) + ETAISYYS_TIEOSAN_ALUSTA_FIELD_NUMBER;
                hash = (53 * hash) + getEtaisyysTieosanAlusta();
            }
            if (hasAjorata()) {
                hash = (37 * hash) + AJORATA_FIELD_NUMBER;
                hash = (53 * hash) + getAjorata();
            }
            if (hasPuoli()) {
                hash = (37 * hash) + PUOLI_FIELD_NUMBER;
                hash = (53 * hash) + getPuoli();
            }
            if (hasXKoordinaatti()) {
                hash = (37 * hash) + X_KOORDINAATTI_FIELD_NUMBER;
                hash = (53 * hash) + getXKoordinaatti().hashCode();
            }
            if (hasYKoordinaatti()) {
                hash = (37 * hash) + Y_KOORDINAATTI_FIELD_NUMBER;
                hash = (53 * hash) + getYKoordinaatti().hashCode();
            }
            if (hasZKoordinaatti()) {
                hash = (37 * hash) + Z_KOORDINAATTI_FIELD_NUMBER;
                hash = (53 * hash) + getZKoordinaatti().hashCode();
            }
            if (hasTtl()) {
                hash = (37 * hash) + TTL_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getTtl());
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static fi.ely.lotju.kamera.proto.KuvaProtos.Kuva parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static fi.ely.lotju.kamera.proto.KuvaProtos.Kuva parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static fi.ely.lotju.kamera.proto.KuvaProtos.Kuva parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static fi.ely.lotju.kamera.proto.KuvaProtos.Kuva parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static fi.ely.lotju.kamera.proto.KuvaProtos.Kuva parseFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }
        public static fi.ely.lotju.kamera.proto.KuvaProtos.Kuva parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static fi.ely.lotju.kamera.proto.KuvaProtos.Kuva parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
        }
        public static fi.ely.lotju.kamera.proto.KuvaProtos.Kuva parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static fi.ely.lotju.kamera.proto.KuvaProtos.Kuva parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }
        public static fi.ely.lotju.kamera.proto.KuvaProtos.Kuva parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(fi.ely.lotju.kamera.proto.KuvaProtos.Kuva prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                   ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code kamera.Kuva}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:kamera.Kuva)
            fi.ely.lotju.kamera.proto.KuvaProtos.KuvaOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return fi.ely.lotju.kamera.proto.KuvaProtos.internal_static_kamera_Kuva_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return fi.ely.lotju.kamera.proto.KuvaProtos.internal_static_kamera_Kuva_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                        fi.ely.lotju.kamera.proto.KuvaProtos.Kuva.class, fi.ely.lotju.kamera.proto.KuvaProtos.Kuva.Builder.class);
            }

            // Construct using fi.ely.lotju.kamera.proto.KuvaProtos.Kuva.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                kameraId_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000001);
                esiasentoId_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                kuvaId_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000004);
                aikaleima_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000008);
                nimi_ = "";
                bitField0_ = (bitField0_ & ~0x00000010);
                esiasennonNimi_ = "";
                bitField0_ = (bitField0_ & ~0x00000020);
                julkinen_ = false;
                bitField0_ = (bitField0_ & ~0x00000040);
                asemanNimi_ = "";
                bitField0_ = (bitField0_ & ~0x00000080);
                liviId_ = "";
                bitField0_ = (bitField0_ & ~0x00000100);
                tienumero_ = 0;
                bitField0_ = (bitField0_ & ~0x00000200);
                tieosa_ = 0;
                bitField0_ = (bitField0_ & ~0x00000400);
                etaisyysTieosanAlusta_ = 0;
                bitField0_ = (bitField0_ & ~0x00000800);
                ajorata_ = 0;
                bitField0_ = (bitField0_ & ~0x00001000);
                puoli_ = 0;
                bitField0_ = (bitField0_ & ~0x00002000);
                xKoordinaatti_ = "";
                bitField0_ = (bitField0_ & ~0x00004000);
                yKoordinaatti_ = "";
                bitField0_ = (bitField0_ & ~0x00008000);
                zKoordinaatti_ = "";
                bitField0_ = (bitField0_ & ~0x00010000);
                ttl_ = 0L;
                bitField0_ = (bitField0_ & ~0x00020000);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return fi.ely.lotju.kamera.proto.KuvaProtos.internal_static_kamera_Kuva_descriptor;
            }

            public fi.ely.lotju.kamera.proto.KuvaProtos.Kuva getDefaultInstanceForType() {
                return fi.ely.lotju.kamera.proto.KuvaProtos.Kuva.getDefaultInstance();
            }

            public fi.ely.lotju.kamera.proto.KuvaProtos.Kuva build() {
                fi.ely.lotju.kamera.proto.KuvaProtos.Kuva result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public fi.ely.lotju.kamera.proto.KuvaProtos.Kuva buildPartial() {
                fi.ely.lotju.kamera.proto.KuvaProtos.Kuva result = new fi.ely.lotju.kamera.proto.KuvaProtos.Kuva(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.kameraId_ = kameraId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.esiasentoId_ = esiasentoId_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.kuvaId_ = kuvaId_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.aikaleima_ = aikaleima_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.nimi_ = nimi_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.esiasennonNimi_ = esiasennonNimi_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000040;
                }
                result.julkinen_ = julkinen_;
                if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
                    to_bitField0_ |= 0x00000080;
                }
                result.asemanNimi_ = asemanNimi_;
                if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
                    to_bitField0_ |= 0x00000100;
                }
                result.liviId_ = liviId_;
                if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
                    to_bitField0_ |= 0x00000200;
                }
                result.tienumero_ = tienumero_;
                if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
                    to_bitField0_ |= 0x00000400;
                }
                result.tieosa_ = tieosa_;
                if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
                    to_bitField0_ |= 0x00000800;
                }
                result.etaisyysTieosanAlusta_ = etaisyysTieosanAlusta_;
                if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
                    to_bitField0_ |= 0x00001000;
                }
                result.ajorata_ = ajorata_;
                if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
                    to_bitField0_ |= 0x00002000;
                }
                result.puoli_ = puoli_;
                if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
                    to_bitField0_ |= 0x00004000;
                }
                result.xKoordinaatti_ = xKoordinaatti_;
                if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
                    to_bitField0_ |= 0x00008000;
                }
                result.yKoordinaatti_ = yKoordinaatti_;
                if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
                    to_bitField0_ |= 0x00010000;
                }
                result.zKoordinaatti_ = zKoordinaatti_;
                if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
                    to_bitField0_ |= 0x00020000;
                }
                result.ttl_ = ttl_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof fi.ely.lotju.kamera.proto.KuvaProtos.Kuva) {
                    return mergeFrom((fi.ely.lotju.kamera.proto.KuvaProtos.Kuva)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(fi.ely.lotju.kamera.proto.KuvaProtos.Kuva other) {
                if (other == fi.ely.lotju.kamera.proto.KuvaProtos.Kuva.getDefaultInstance()) return this;
                if (other.hasKameraId()) {
                    setKameraId(other.getKameraId());
                }
                if (other.hasEsiasentoId()) {
                    setEsiasentoId(other.getEsiasentoId());
                }
                if (other.hasKuvaId()) {
                    setKuvaId(other.getKuvaId());
                }
                if (other.hasAikaleima()) {
                    setAikaleima(other.getAikaleima());
                }
                if (other.hasNimi()) {
                    bitField0_ |= 0x00000010;
                    nimi_ = other.nimi_;
                    onChanged();
                }
                if (other.hasEsiasennonNimi()) {
                    bitField0_ |= 0x00000020;
                    esiasennonNimi_ = other.esiasennonNimi_;
                    onChanged();
                }
                if (other.hasJulkinen()) {
                    setJulkinen(other.getJulkinen());
                }
                if (other.hasAsemanNimi()) {
                    bitField0_ |= 0x00000080;
                    asemanNimi_ = other.asemanNimi_;
                    onChanged();
                }
                if (other.hasLiviId()) {
                    bitField0_ |= 0x00000100;
                    liviId_ = other.liviId_;
                    onChanged();
                }
                if (other.hasTienumero()) {
                    setTienumero(other.getTienumero());
                }
                if (other.hasTieosa()) {
                    setTieosa(other.getTieosa());
                }
                if (other.hasEtaisyysTieosanAlusta()) {
                    setEtaisyysTieosanAlusta(other.getEtaisyysTieosanAlusta());
                }
                if (other.hasAjorata()) {
                    setAjorata(other.getAjorata());
                }
                if (other.hasPuoli()) {
                    setPuoli(other.getPuoli());
                }
                if (other.hasXKoordinaatti()) {
                    bitField0_ |= 0x00004000;
                    xKoordinaatti_ = other.xKoordinaatti_;
                    onChanged();
                }
                if (other.hasYKoordinaatti()) {
                    bitField0_ |= 0x00008000;
                    yKoordinaatti_ = other.yKoordinaatti_;
                    onChanged();
                }
                if (other.hasZKoordinaatti()) {
                    bitField0_ |= 0x00010000;
                    zKoordinaatti_ = other.zKoordinaatti_;
                    onChanged();
                }
                if (other.hasTtl()) {
                    setTtl(other.getTtl());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                if (!hasKameraId()) {
                    return false;
                }
                if (!hasEsiasentoId()) {
                    return false;
                }
                if (!hasKuvaId()) {
                    return false;
                }
                if (!hasAikaleima()) {
                    return false;
                }
                if (!hasNimi()) {
                    return false;
                }
                if (!hasEsiasennonNimi()) {
                    return false;
                }
                if (!hasJulkinen()) {
                    return false;
                }
                if (!hasAsemanNimi()) {
                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                fi.ely.lotju.kamera.proto.KuvaProtos.Kuva parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (fi.ely.lotju.kamera.proto.KuvaProtos.Kuva) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private long kameraId_ ;
            /**
             * <code>required int64 kamera_id = 1;</code>
             */
            public boolean hasKameraId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>required int64 kamera_id = 1;</code>
             */
            public long getKameraId() {
                return kameraId_;
            }
            /**
             * <code>required int64 kamera_id = 1;</code>
             */
            public Builder setKameraId(long value) {
                bitField0_ |= 0x00000001;
                kameraId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required int64 kamera_id = 1;</code>
             */
            public Builder clearKameraId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                kameraId_ = 0L;
                onChanged();
                return this;
            }

            private long esiasentoId_ ;
            /**
             * <code>required int64 esiasento_id = 2;</code>
             */
            public boolean hasEsiasentoId() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            /**
             * <code>required int64 esiasento_id = 2;</code>
             */
            public long getEsiasentoId() {
                return esiasentoId_;
            }
            /**
             * <code>required int64 esiasento_id = 2;</code>
             */
            public Builder setEsiasentoId(long value) {
                bitField0_ |= 0x00000002;
                esiasentoId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required int64 esiasento_id = 2;</code>
             */
            public Builder clearEsiasentoId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                esiasentoId_ = 0L;
                onChanged();
                return this;
            }

            private long kuvaId_ ;
            /**
             * <code>required int64 kuva_id = 3;</code>
             */
            public boolean hasKuvaId() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }
            /**
             * <code>required int64 kuva_id = 3;</code>
             */
            public long getKuvaId() {
                return kuvaId_;
            }
            /**
             * <code>required int64 kuva_id = 3;</code>
             */
            public Builder setKuvaId(long value) {
                bitField0_ |= 0x00000004;
                kuvaId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required int64 kuva_id = 3;</code>
             */
            public Builder clearKuvaId() {
                bitField0_ = (bitField0_ & ~0x00000004);
                kuvaId_ = 0L;
                onChanged();
                return this;
            }

            private long aikaleima_ ;
            /**
             * <code>required int64 aikaleima = 4;</code>
             */
            public boolean hasAikaleima() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }
            /**
             * <code>required int64 aikaleima = 4;</code>
             */
            public long getAikaleima() {
                return aikaleima_;
            }
            /**
             * <code>required int64 aikaleima = 4;</code>
             */
            public Builder setAikaleima(long value) {
                bitField0_ |= 0x00000008;
                aikaleima_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required int64 aikaleima = 4;</code>
             */
            public Builder clearAikaleima() {
                bitField0_ = (bitField0_ & ~0x00000008);
                aikaleima_ = 0L;
                onChanged();
                return this;
            }

            private java.lang.Object nimi_ = "";
            /**
             * <code>required string nimi = 5;</code>
             */
            public boolean hasNimi() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }
            /**
             * <code>required string nimi = 5;</code>
             */
            public java.lang.String getNimi() {
                java.lang.Object ref = nimi_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        nimi_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string nimi = 5;</code>
             */
            public com.google.protobuf.ByteString
            getNimiBytes() {
                java.lang.Object ref = nimi_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    nimi_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string nimi = 5;</code>
             */
            public Builder setNimi(
                java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                nimi_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string nimi = 5;</code>
             */
            public Builder clearNimi() {
                bitField0_ = (bitField0_ & ~0x00000010);
                nimi_ = getDefaultInstance().getNimi();
                onChanged();
                return this;
            }
            /**
             * <code>required string nimi = 5;</code>
             */
            public Builder setNimiBytes(
                com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                nimi_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object esiasennonNimi_ = "";
            /**
             * <code>required string esiasennon_nimi = 6;</code>
             */
            public boolean hasEsiasennonNimi() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }
            /**
             * <code>required string esiasennon_nimi = 6;</code>
             */
            public java.lang.String getEsiasennonNimi() {
                java.lang.Object ref = esiasennonNimi_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        esiasennonNimi_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string esiasennon_nimi = 6;</code>
             */
            public com.google.protobuf.ByteString
            getEsiasennonNimiBytes() {
                java.lang.Object ref = esiasennonNimi_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    esiasennonNimi_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string esiasennon_nimi = 6;</code>
             */
            public Builder setEsiasennonNimi(
                java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000020;
                esiasennonNimi_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string esiasennon_nimi = 6;</code>
             */
            public Builder clearEsiasennonNimi() {
                bitField0_ = (bitField0_ & ~0x00000020);
                esiasennonNimi_ = getDefaultInstance().getEsiasennonNimi();
                onChanged();
                return this;
            }
            /**
             * <code>required string esiasennon_nimi = 6;</code>
             */
            public Builder setEsiasennonNimiBytes(
                com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000020;
                esiasennonNimi_ = value;
                onChanged();
                return this;
            }

            private boolean julkinen_ ;
            /**
             * <code>required bool julkinen = 7;</code>
             */
            public boolean hasJulkinen() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }
            /**
             * <code>required bool julkinen = 7;</code>
             */
            public boolean getJulkinen() {
                return julkinen_;
            }
            /**
             * <code>required bool julkinen = 7;</code>
             */
            public Builder setJulkinen(boolean value) {
                bitField0_ |= 0x00000040;
                julkinen_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required bool julkinen = 7;</code>
             */
            public Builder clearJulkinen() {
                bitField0_ = (bitField0_ & ~0x00000040);
                julkinen_ = false;
                onChanged();
                return this;
            }

            private java.lang.Object asemanNimi_ = "";
            /**
             * <code>required string aseman_nimi = 8;</code>
             */
            public boolean hasAsemanNimi() {
                return ((bitField0_ & 0x00000080) == 0x00000080);
            }
            /**
             * <code>required string aseman_nimi = 8;</code>
             */
            public java.lang.String getAsemanNimi() {
                java.lang.Object ref = asemanNimi_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        asemanNimi_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string aseman_nimi = 8;</code>
             */
            public com.google.protobuf.ByteString
            getAsemanNimiBytes() {
                java.lang.Object ref = asemanNimi_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    asemanNimi_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string aseman_nimi = 8;</code>
             */
            public Builder setAsemanNimi(
                java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000080;
                asemanNimi_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string aseman_nimi = 8;</code>
             */
            public Builder clearAsemanNimi() {
                bitField0_ = (bitField0_ & ~0x00000080);
                asemanNimi_ = getDefaultInstance().getAsemanNimi();
                onChanged();
                return this;
            }
            /**
             * <code>required string aseman_nimi = 8;</code>
             */
            public Builder setAsemanNimiBytes(
                com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000080;
                asemanNimi_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object liviId_ = "";
            /**
             * <code>optional string liviId = 9;</code>
             */
            public boolean hasLiviId() {
                return ((bitField0_ & 0x00000100) == 0x00000100);
            }
            /**
             * <code>optional string liviId = 9;</code>
             */
            public java.lang.String getLiviId() {
                java.lang.Object ref = liviId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        liviId_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string liviId = 9;</code>
             */
            public com.google.protobuf.ByteString
            getLiviIdBytes() {
                java.lang.Object ref = liviId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    liviId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string liviId = 9;</code>
             */
            public Builder setLiviId(
                java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000100;
                liviId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string liviId = 9;</code>
             */
            public Builder clearLiviId() {
                bitField0_ = (bitField0_ & ~0x00000100);
                liviId_ = getDefaultInstance().getLiviId();
                onChanged();
                return this;
            }
            /**
             * <code>optional string liviId = 9;</code>
             */
            public Builder setLiviIdBytes(
                com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000100;
                liviId_ = value;
                onChanged();
                return this;
            }

            private int tienumero_ ;
            /**
             * <code>optional int32 tienumero = 10;</code>
             */
            public boolean hasTienumero() {
                return ((bitField0_ & 0x00000200) == 0x00000200);
            }
            /**
             * <code>optional int32 tienumero = 10;</code>
             */
            public int getTienumero() {
                return tienumero_;
            }
            /**
             * <code>optional int32 tienumero = 10;</code>
             */
            public Builder setTienumero(int value) {
                bitField0_ |= 0x00000200;
                tienumero_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int32 tienumero = 10;</code>
             */
            public Builder clearTienumero() {
                bitField0_ = (bitField0_ & ~0x00000200);
                tienumero_ = 0;
                onChanged();
                return this;
            }

            private int tieosa_ ;
            /**
             * <code>optional int32 tieosa = 11;</code>
             */
            public boolean hasTieosa() {
                return ((bitField0_ & 0x00000400) == 0x00000400);
            }
            /**
             * <code>optional int32 tieosa = 11;</code>
             */
            public int getTieosa() {
                return tieosa_;
            }
            /**
             * <code>optional int32 tieosa = 11;</code>
             */
            public Builder setTieosa(int value) {
                bitField0_ |= 0x00000400;
                tieosa_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int32 tieosa = 11;</code>
             */
            public Builder clearTieosa() {
                bitField0_ = (bitField0_ & ~0x00000400);
                tieosa_ = 0;
                onChanged();
                return this;
            }

            private int etaisyysTieosanAlusta_ ;
            /**
             * <code>optional int32 etaisyys_tieosan_alusta = 12;</code>
             */
            public boolean hasEtaisyysTieosanAlusta() {
                return ((bitField0_ & 0x00000800) == 0x00000800);
            }
            /**
             * <code>optional int32 etaisyys_tieosan_alusta = 12;</code>
             */
            public int getEtaisyysTieosanAlusta() {
                return etaisyysTieosanAlusta_;
            }
            /**
             * <code>optional int32 etaisyys_tieosan_alusta = 12;</code>
             */
            public Builder setEtaisyysTieosanAlusta(int value) {
                bitField0_ |= 0x00000800;
                etaisyysTieosanAlusta_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int32 etaisyys_tieosan_alusta = 12;</code>
             */
            public Builder clearEtaisyysTieosanAlusta() {
                bitField0_ = (bitField0_ & ~0x00000800);
                etaisyysTieosanAlusta_ = 0;
                onChanged();
                return this;
            }

            private int ajorata_ ;
            /**
             * <code>optional int32 ajorata = 13;</code>
             */
            public boolean hasAjorata() {
                return ((bitField0_ & 0x00001000) == 0x00001000);
            }
            /**
             * <code>optional int32 ajorata = 13;</code>
             */
            public int getAjorata() {
                return ajorata_;
            }
            /**
             * <code>optional int32 ajorata = 13;</code>
             */
            public Builder setAjorata(int value) {
                bitField0_ |= 0x00001000;
                ajorata_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int32 ajorata = 13;</code>
             */
            public Builder clearAjorata() {
                bitField0_ = (bitField0_ & ~0x00001000);
                ajorata_ = 0;
                onChanged();
                return this;
            }

            private int puoli_ ;
            /**
             * <code>optional int32 puoli = 14;</code>
             */
            public boolean hasPuoli() {
                return ((bitField0_ & 0x00002000) == 0x00002000);
            }
            /**
             * <code>optional int32 puoli = 14;</code>
             */
            public int getPuoli() {
                return puoli_;
            }
            /**
             * <code>optional int32 puoli = 14;</code>
             */
            public Builder setPuoli(int value) {
                bitField0_ |= 0x00002000;
                puoli_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int32 puoli = 14;</code>
             */
            public Builder clearPuoli() {
                bitField0_ = (bitField0_ & ~0x00002000);
                puoli_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object xKoordinaatti_ = "";
            /**
             * <code>optional string x_koordinaatti = 15;</code>
             */
            public boolean hasXKoordinaatti() {
                return ((bitField0_ & 0x00004000) == 0x00004000);
            }
            /**
             * <code>optional string x_koordinaatti = 15;</code>
             */
            public java.lang.String getXKoordinaatti() {
                java.lang.Object ref = xKoordinaatti_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        xKoordinaatti_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string x_koordinaatti = 15;</code>
             */
            public com.google.protobuf.ByteString
            getXKoordinaattiBytes() {
                java.lang.Object ref = xKoordinaatti_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    xKoordinaatti_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string x_koordinaatti = 15;</code>
             */
            public Builder setXKoordinaatti(
                java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00004000;
                xKoordinaatti_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string x_koordinaatti = 15;</code>
             */
            public Builder clearXKoordinaatti() {
                bitField0_ = (bitField0_ & ~0x00004000);
                xKoordinaatti_ = getDefaultInstance().getXKoordinaatti();
                onChanged();
                return this;
            }
            /**
             * <code>optional string x_koordinaatti = 15;</code>
             */
            public Builder setXKoordinaattiBytes(
                com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00004000;
                xKoordinaatti_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object yKoordinaatti_ = "";
            /**
             * <code>optional string y_koordinaatti = 16;</code>
             */
            public boolean hasYKoordinaatti() {
                return ((bitField0_ & 0x00008000) == 0x00008000);
            }
            /**
             * <code>optional string y_koordinaatti = 16;</code>
             */
            public java.lang.String getYKoordinaatti() {
                java.lang.Object ref = yKoordinaatti_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        yKoordinaatti_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string y_koordinaatti = 16;</code>
             */
            public com.google.protobuf.ByteString
            getYKoordinaattiBytes() {
                java.lang.Object ref = yKoordinaatti_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    yKoordinaatti_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string y_koordinaatti = 16;</code>
             */
            public Builder setYKoordinaatti(
                java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00008000;
                yKoordinaatti_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string y_koordinaatti = 16;</code>
             */
            public Builder clearYKoordinaatti() {
                bitField0_ = (bitField0_ & ~0x00008000);
                yKoordinaatti_ = getDefaultInstance().getYKoordinaatti();
                onChanged();
                return this;
            }
            /**
             * <code>optional string y_koordinaatti = 16;</code>
             */
            public Builder setYKoordinaattiBytes(
                com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00008000;
                yKoordinaatti_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object zKoordinaatti_ = "";
            /**
             * <code>optional string z_koordinaatti = 17;</code>
             */
            public boolean hasZKoordinaatti() {
                return ((bitField0_ & 0x00010000) == 0x00010000);
            }
            /**
             * <code>optional string z_koordinaatti = 17;</code>
             */
            public java.lang.String getZKoordinaatti() {
                java.lang.Object ref = zKoordinaatti_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        zKoordinaatti_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string z_koordinaatti = 17;</code>
             */
            public com.google.protobuf.ByteString
            getZKoordinaattiBytes() {
                java.lang.Object ref = zKoordinaatti_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    zKoordinaatti_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string z_koordinaatti = 17;</code>
             */
            public Builder setZKoordinaatti(
                java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00010000;
                zKoordinaatti_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string z_koordinaatti = 17;</code>
             */
            public Builder clearZKoordinaatti() {
                bitField0_ = (bitField0_ & ~0x00010000);
                zKoordinaatti_ = getDefaultInstance().getZKoordinaatti();
                onChanged();
                return this;
            }
            /**
             * <code>optional string z_koordinaatti = 17;</code>
             */
            public Builder setZKoordinaattiBytes(
                com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00010000;
                zKoordinaatti_ = value;
                onChanged();
                return this;
            }

            private long ttl_ ;
            /**
             * <code>optional int64 ttl = 18;</code>
             */
            public boolean hasTtl() {
                return ((bitField0_ & 0x00020000) == 0x00020000);
            }
            /**
             * <code>optional int64 ttl = 18;</code>
             */
            public long getTtl() {
                return ttl_;
            }
            /**
             * <code>optional int64 ttl = 18;</code>
             */
            public Builder setTtl(long value) {
                bitField0_ |= 0x00020000;
                ttl_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int64 ttl = 18;</code>
             */
            public Builder clearTtl() {
                bitField0_ = (bitField0_ & ~0x00020000);
                ttl_ = 0L;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:kamera.Kuva)
        }

        // @@protoc_insertion_point(class_scope:kamera.Kuva)
        private static final fi.ely.lotju.kamera.proto.KuvaProtos.Kuva DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new fi.ely.lotju.kamera.proto.KuvaProtos.Kuva();
        }

        public static fi.ely.lotju.kamera.proto.KuvaProtos.Kuva getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated public static final com.google.protobuf.Parser<Kuva>
            PARSER = new com.google.protobuf.AbstractParser<Kuva>() {
            public Kuva parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
                return new Kuva(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Kuva> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Kuva> getParserForType() {
            return PARSER;
        }

        public fi.ely.lotju.kamera.proto.KuvaProtos.Kuva getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
        internal_static_kamera_Kuva_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_kamera_Kuva_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
        descriptor;
    static {
        java.lang.String[] descriptorData = {
            "\n\nkuva.proto\022\006kamera\"\352\002\n\004Kuva\022\021\n\tkamera_" +
                "id\030\001 \002(\003\022\024\n\014esiasento_id\030\002 \002(\003\022\017\n\007kuva_i" +
                "d\030\003 \002(\003\022\021\n\taikaleima\030\004 \002(\003\022\014\n\004nimi\030\005 \002(\t" +
                "\022\027\n\017esiasennon_nimi\030\006 \002(\t\022\020\n\010julkinen\030\007 " +
                "\002(\010\022\023\n\013aseman_nimi\030\010 \002(\t\022\016\n\006liviId\030\t \001(\t" +
                "\022\021\n\ttienumero\030\n \001(\005\022\016\n\006tieosa\030\013 \001(\005\022\037\n\027e" +
                "taisyys_tieosan_alusta\030\014 \001(\005\022\017\n\007ajorata\030" +
                "\r \001(\005\022\r\n\005puoli\030\016 \001(\005\022\026\n\016x_koordinaatti\030\017" +
                " \001(\t\022\026\n\016y_koordinaatti\030\020 \001(\t\022\026\n\016z_koordi" +
                "naatti\030\021 \001(\t\022\013\n\003ttl\030\022 \001(\003B\'\n\031fi.ely.lotj",
            "u.kamera.protoB\nKuvaProtos"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                    descriptor = root;
                    return null;
                }
            };
        com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {
                }, assigner);
        internal_static_kamera_Kuva_descriptor =
            getDescriptor().getMessageTypes().get(0);
        internal_static_kamera_Kuva_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_kamera_Kuva_descriptor,
            new java.lang.String[] { "KameraId", "EsiasentoId", "KuvaId", "Aikaleima", "Nimi", "EsiasennonNimi", "Julkinen", "AsemanNimi", "LiviId", "Tienumero", "Tieosa", "EtaisyysTieosanAlusta", "Ajorata", "Puoli", "XKoordinaatti", "YKoordinaatti", "ZKoordinaatti", "Ttl", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}