--select 'insert into location_type(version, type_code, description_en, description_fi) values(''' || version || ''',''' || type_code ||
--''',''' || description_en || ''',''' || description_fi || ''');'
--from location_type where version in ('1.11.34', '1.11.33');

insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','A1.0','Continent','Maanosa');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','A10.0','4th order area','Kaupunginosa');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','A11.0','5th order area','Order 5 area');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','A12.0','Application area','Application area');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','A2.0','Country group','Maaryhmä');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','A3.0','Country','Maa');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','A5.0','Water area','Vesistöalue');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','A6.0','Fuzzy area','Fuzzy area');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','A7.0','1st order area','AVI-alue');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','A8.0','2nd order area','Maakunta');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','A9.0','3rd order area','Kunta');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','L1.0','Road','Tie');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','L2.0','Ring road','Kehätie');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','L3.0','1st order segment','1. Asteen tiejakso');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','L4.0','2nd order segment','2. Asteen tiejakso');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','L5.0','Urban street','Taajamatie');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','L6.0','Vehicular link','Vehicular link');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','L7.0','Link road','Link road');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','P1.0','Junction','Liittymä');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','P2.0','Intermediate point','Tekninen piste');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','P3.0','Other landmark point','Muu piste');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','P4.0','Link road point','Link road point');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.33','P5.0','Parking POI','Parking POI');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','A1.0','Continent','Maanosa');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','A10.0','4th order area','Kaupunginosa');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','A11.0','5th order area','Order 5 area');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','A12.0','Application area','Application area');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','A2.0','Country group','Maaryhmä');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','A3.0','Country','Maa');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','A5.0','Water area','Vesistöalue');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','A6.0','Fuzzy area','Fuzzy area');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','A7.0','1st order area','AVI-alue');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','A8.0','2nd order area','Maakunta');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','A9.0','3rd order area','Kunta');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','L1.0','Road','Tie');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','L2.0','Ring road','Kehätie');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','L3.0','1st order segment','1. Asteen tiejakso');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','L4.0','2nd order segment','2. Asteen tiejakso');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','L5.0','Urban street','Taajamatie');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','L6.0','Vehicular link','Vehicular link');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','L7.0','Link road','Link road');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','P1.0','Junction','Liittymä');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','P2.0','Intermediate point','Tekninen piste');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','P3.0','Other landmark point','Muu piste');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','P4.0','Link road point','Link road point');
insert into location_type(version, type_code, description_en, description_fi) values('1.11.34','P5.0','Parking POI','Parking POI');