
DO $$ BEGIN
  CREATE TYPE maintenance_task_enum AS ENUM (
    'BRUSHING','BRUSH_CLEARING','CLEANSING_OF_BRIDGES','CLEANSING_OF_REST_AREAS','CLEANSING_OF_TRAFFIC_SIGNS','CLIENTS_QUALITY_CONTROL','COMPACTION_BY_ROLLING','CRACK_FILLING','DITCHING','DUST_BINDING_OF_GRAVEL_ROAD_SURFACE','FILLING_OF_GRAVEL_ROAD_SHOULDERS','FILLING_OF_ROAD_SHOULDERS','HEATING','LEVELLING_GRAVEL_ROAD_SURFACE','LEVELLING_OF_ROAD_SHOULDERS','LEVELLING_OF_ROAD_SURFACE','LINE_SANDING','LOWERING_OF_SNOWBANKS','MAINTENANCE_OF_GUIDE_SIGNS_AND_REFLECTOR_POSTS','MECHANICAL_CUT','MIXING_OR_STABILIZATION','OTHER','PATCHING','PAVING','PLOUGHING_AND_SLUSH_REMOVAL','PREVENTING_MELTING_WATER_PROBLEMS','REMOVAL_OF_BULGE_ICE','RESHAPING_GRAVEL_ROAD_SURFACE','ROAD_INSPECTIONS','ROAD_MARKINGS','ROAD_STATE_CHECKING','SAFETY_EQUIPMENT','SALTING','SNOW_PLOUGHING_STICKS_AND_SNOW_FENCES','SPOT_SANDING','SPREADING_OF_CRUSH','TRANSFER_OF_SNOW','UNKNOWN'
  );
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

ALTER TABLE maintenance_tracking
  ADD COLUMN IF NOT EXISTS tasks maintenance_task_enum[];

WITH src_tasks AS (
  SELECT maintenance_tracking_id AS tracking_id, array_agg(task)::maintenance_task_enum[] AS tasks
  FROM maintenance_tracking_task
  GROUP BY maintenance_tracking_id
)
UPDATE maintenance_tracking
SET tasks = src_tasks.tasks
FROM src_tasks
WHERE maintenance_tracking.id = src_tasks.tracking_id
  AND maintenance_tracking.tasks IS NULL;

CREATE INDEX IF NOT EXISTS maintenance_tracking_tasks_i ON maintenance_tracking USING GIN (tasks);
