INSERT INTO maintenance_tracking_task_value (name, name_harja, name_fi, name_sv, name_en)
VALUES
  ('BRUSHING', 'HARJAUS', 'Harjaus', 'Borstning', 'Brushing'),
  ('BRUSH_CLEARING', 'KONEELLINEN_VESAKONRAIVAUS', 'Koneellinen vesakonraivaus', 'Slyklippning', 'Brush clearing'),
  ('CLEANSING_OF_BRIDGES', 'SILTOJEN_PUHDISTUS', 'Siltojen puhdistus', 'Rengöring av broar', 'Cleansing of bridges'),
  ('CLEANSING_OF_REST_AREAS', 'L_JA_P_ALUEIDEN_PUHDISTUS', 'L- ja p-alueiden puhdistus', 'Rast- och parkeringsplatsernas rengöring', 'Cleansing of rest areas'),
  ('CLEANSING_OF_TRAFFIC_SIGNS', 'LIIKENNEMERKKIEN_PUHDISTUS', 'Liikennemerkkien puhdistus', 'Rengöring av trafikmärken', 'Cleansing of traffic signs'),
  ('CLIENTS_QUALITY_CONTROL', 'TILAAJAN_LAADUNVALVONTA', 'Tilaajan laadunvalvonta', 'Beställarens kvalitetsövervakning', 'Clients quality control'),
  ('COMPACTION_BY_ROLLING', 'JYRAYS', 'Jyräys', 'Vibrering', 'Compaction by rolling'),
  ('CRACK_FILLING', 'PAALLYSTEIDEN_JUOTOSTYOT', 'Päällysteiden juotostyöt', 'Fyllning av sprickor i beläggningen', 'Crack filling'),
  ('DITCHING', 'OJITUS', 'Ojitus', 'Dikning', 'Ditching'),
  ('DUST_BINDING_OF_GRAVEL_ROAD_SURFACE', 'SORATEIDEN_POLYNSIDONTA', 'Sorateiden pölynsidonta', 'Dammbindning av grusväg', 'Dust binding of gravel road surface'),
  ('FILLING_OF_GRAVEL_ROAD_SHOULDERS', 'SORAPIENTAREEN_TAYTTO', 'Sorapientareen täyttö', 'Fyllning av grusväg gruskanter', 'Filling of gravel road shoulders'),
  ('FILLING_OF_ROAD_SHOULDERS', 'PAALLYSTETYN_TIEN_SORAPIENTAREEN_TAYTTO', 'Päällystetyn tien sorapientareen täyttö', 'Belagda vägars kantfyllning', 'Filling of paved road shoulders'),
  ('HEATING', 'KUUMENNUS', 'Kuumennus', 'Upphettning', 'Heating'),
  ('LEVELLING_GRAVEL_ROAD_SURFACE', 'SORATEIDEN_TASAUS', 'Sorateiden tasaus', 'Utjämning av grusväg', 'Levelling gravel road surface'),
  ('LEVELLING_OF_ROAD_SHOULDERS', 'PALTEEN_POISTO', 'Palteen poisto', 'Kantskärning', 'Levelling of road shoulders'),
  ('LEVELLING_OF_ROAD_SURFACE', 'PINNAN_TASAUS', 'Pinnan tasaus', 'Utjämning av vägytan', 'Levelling of road surface'),
  ('LINE_SANDING', 'LINJAHIEKOITUS', 'Linjahiekoitus', 'Linjesandning', 'Line sanding'),
  ('LOWERING_OF_SNOWBANKS', 'LUMIVALLIEN_MADALTAMINEN', 'Lumivallien madaltaminen', 'Nedsänkning av plogvall', 'Lowering of snowbanks'),
  ('MAINTENANCE_OF_GUIDE_SIGNS_AND_REFLECTOR_POSTS', 'LIIK_OPAST_JA_OHJAUSL_HOITO_SEKA_REUNAPAALUJEN_KUN_PITO', 'Liikenteen opasteiden ja ohjauslaitteiden hoito sekä reunapaalujen kunnossapito', 'Trafikanordningars och kantpålars underhåll', 'Maintenance of guide signs and reflector posts'),
  ('MECHANICAL_CUT', 'KONEELLINEN_NIITTO', 'Koneellinen niitto', 'Mekanisk klippning', 'Mechanical cut'),
  ('MIXING_OR_STABILIZATION', 'SEKOITUS_TAI_STABILOINTI', 'Sekoitus tai stabilointi', 'Blandning och stabilisering', 'Mixing or stabilization'),
  ('OTHER', 'MUU', 'Muu', 'Annat dylikt', 'Other'),
  ('PATCHING', 'PAALLYSTEIDEN_PAIKKAUS', 'Päällysteiden paikkaus', 'Lappning av beläggning', 'Patching'),
  ('PAVING', 'ASFALTOINTI', 'Asfaltointi', 'Asfaltering', 'Paving'),
  ('PLOUGHING_AND_SLUSH_REMOVAL', 'AURAUS_JA_SOHJONPOISTO', 'Auraus ja sohjonpoisto', 'Plog- och sörjröjning', 'Ploughing and slush removal'),
  ('PREVENTING_MELTING_WATER_PROBLEMS', 'SULAMISVEDEN_HAITTOJEN_TORJUNTA', 'Sulamisveden haittojen torjunta', 'Smältvattensbekämpning', 'Preventing melting water problems'),
  ('REMOVAL_OF_BULGE_ICE', 'PAANNEJAAN_POISTO', 'Paannejään poisto', 'Borttagning av svall-is', 'Removal of bulge ice'),
  ('RESHAPING_GRAVEL_ROAD_SURFACE', 'SORATEIDEN_MUOKKAUSHOYLAYS', 'Sorateiden muokkaushöyläys', 'Grusvägsytans omblandning ', 'Reshaping gravel road surface'),
  ('ROAD_INSPECTIONS', 'TIESTOTARKASTUS', 'Tiestötarkastus', 'Väggranskning', 'Road inspections '),
  ('ROAD_MARKINGS', 'TIEMERKINTA', 'Tiemerkintä', 'Vägmarkering', 'Road markings'),
  ('ROAD_STATE_CHECKING', 'KELINTARKASTUS', 'Kelintarkastus', 'Väglagsgranskning', 'Road state checking'),
  ('SAFETY_EQUIPMENT', 'TURVALAITE', 'Turvalaite', 'Säkerhetsanordning', 'Safety equipment'),
  ('SALTING', 'SUOLAUS', 'Suolaus', 'Saltning', 'Salting'),
  ('SNOW_PLOUGHING_STICKS_AND_SNOW_FENCES', 'AURAUSVIITOITUS_JA_KINOSTIMET', 'Aurausviitoitus ja kinostimet', 'Plogkäppsmarkering och snödrivor', 'Snow-ploughing sticks and snow fences'),
  ('SPOT_SANDING', 'PISTEHIEKOITUS', 'Pistehiekoitus', 'Punktsandning', 'Spot sanding'),
  ('SPREADING_OF_CRUSH', 'SORASTUS', 'Sorastus', 'Grusning', 'Spreading of crush'),
  ('TRANSFER_OF_SNOW', 'LUMENSIIRTO', 'Lumensiirto', 'Bortforsling av snömassor', 'Transfer of snow'),
  ('SERVICE_ROUND', 'HUOLTOKIERROS', 'Huoltokierros', 'Servicerunda', 'Service round'),
  ('ENSURING_TRAFFIC_IN_RASPUTITSA', 'LIIKENTEEN_VARMISTAMINEN_KELIRIKKOKOHTEESSA', 'Liikenteen varmistaminen kelirikkokohteessa', 'Säkra trafik i menföre', 'Ensuring traffic in frost heave damage location'),
  ('OTHER_OPERATIONS_OF_LIGHTING_CONTRACTS', 'MUUT_VALAISTUSURAKOIDEN_TOIMENPITEET', 'Muut valaistusurakoiden toimenpiteet', 'Andra mått på belysningskontrakt', 'Other operations of lighting contracts'),
  ('LEVELLING_OF_ROAD_SHOULDERS_UNDER_RAILING', 'PALTEEN_POISTO_KAITEEN_ALTA', 'Palteen poisto kaiteen alta', 'Kantskärning från under räcket', 'Levelling of road shoulders under the railing'),
  ('DUST_BINDING_OF_PAVED_ROAD_SURFACE', 'PAALLYSTETYN_TIEN_POLYNSIDONTA', 'Paallystetyn tien polynsidonta', 'Dammbindning av belagda väg', 'Dust binding of paved road surface'),
  ('RENEWAL_OF_EDGE_COLUMNS', 'REUNAPAALUJEN_UUSIMINEN', 'Reunapaalujen uusiminen', 'Förnyelse av reflektorstolpe', 'Renewal of reflector posts'),
  ('GARBAGE_OLLECTION', 'ROSKIEN_KERUU', 'Roskien keruu', 'Sophämtning', 'Garbage collection'),
  ('GROUP_REPLACEMENT_OF_LAMPS', 'RYHMAVAIHTO', 'Valaisimien ryhmavaihto', 'Gruppbyte av lampor', 'Group replacement of lamps'),
  ('PLOUGHING_OF_SLUSH_DITCH', 'SOHJO_OJIEN_TEKO', 'Sohjo-ojien teko', 'Plöjning av slask dike', 'Ploughing of slush ditch'),
  ('UNKNOWN', 'TUNTEMATON', 'Tuntematon', 'Obekant', 'Unknown')
on conflict (name) do update
  SET name_harja = excluded.name_harja
    , name_fi = excluded.name_fi
    , name_sv = excluded.name_sv
    , name_en = excluded.name_en;
