CREATE TABLE IF NOT EXISTS datex2_rtti (
                                         datex2_id				integer primary key generated by default as identity,
                                         situation_id		    text not null,
                                         type					text not null,
                                         publication_time		TIMESTAMP with TIME zone not null,
                                         geometry				geometry not null,
                                         start_time				TIMESTAMP with TIME zone not null,
                                         end_time				TIMESTAMP with TIME zone,
                                         is_srti				boolean not null,
                                         message 		      	text not null,
--
                                         created_at      		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  modified_at     		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
  );

create index if not exists datex2_rtti_situation_publication_time on datex2_rtti(situation_id, publication_time);
create index if not exists datex2_rtti_start_time on datex2_rtti(start_time, situation_id, publication_time);
