create table data_datex2_situation (
     datex2_id					        integer primary key generated by default as identity,
     situation_id				        text not null,
     situation_type				      text not null,
     situation_version			    integer not null,
     publication_time			TIMESTAMP with TIME zone not null,
     geometry					    geometry not null,
     start_time					  TIMESTAMP with TIME zone not null,
     end_time					    TIMESTAMP with TIME zone,
--
     created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
     modified_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

create table data_datex2_situation_message (
     message_id	      integer primary key generated by default as identity,
     datex2_id	      integer not null references data_datex2_situation(datex2_id),
--
     message_version	text not null,
     message_type 	  text not null,
     message 		      text not null
);

alter table data_datex2_situation_message add constraint data_datex2_situation_message_key unique (datex2_id, message_version, message_type);

create unique index data_datex2_situation_search_key on data_datex2_situation(situation_id, situation_version desc) include (datex2_id);
create unique index data_datex2_situation_search_by_type_key on data_datex2_situation(situation_type, situation_id, situation_version desc);
