create table data_incoming (
    data_id			integer primary key generated by default as identity,
    message_id	text not null,
    source			text not null,
    version			text not null,
    type			  text not null,
    data			  text not null,
    status			text not null check (status in ('NEW', 'FAILED', 'PROCESSED')),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    modified_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

create index data_incoming_source_type_i on data_incoming(source, type) where status = 'NEW';
create index data_incoming_created_i on data_incoming(created_at);
