package fi.livi.digitraffic.tie.model;

public enum DataSource {

    TMS_STATION,
    TMS_STATION_DATA,
    WEATHER_STATION,
    WEATHER_STATION_DATA,
    WEATHERCAM_STATION,
    WEATHERCAM_STATION_DATA,
    VARIABLE_SIGN,
    VARIABLE_SIGN_DATA,
    TRAFFIC_MESSAGE,
    TRAFFIC_MESSAGE_AREA,
    TRAFFIC_MESSAGE_LOCATION,
    FORECAST_SECTION,
    FORECAST_SECTION_FORECAST,
    MAINTENANCE_TRACKING,
    MAINTENANCE_TRACKING_MUNICIPALITY,
    COUNTING_SITE,
    COUNTING_SITE_DATA
}
