name: "Mirror repo to public"
on:
  push:
    branches:
      - master
jobs:
  Mirror-action:
    if: github.repository != 'tmfg/digitraffic-road'
    runs-on: ubuntu-24.04
    steps:
      - name: Mirror
        uses: tmfg/digitraffic-actions@mirror/v2
        with:
          mirror-repo: git@github.com:tmfg/digitraffic-road.git
          ssh-private-key: ${{ secrets.SSH_MIRROR_KEY }}
