name: Update Fargate Service
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        type: environment
        default: "test"
      family-name:
        description: "Which service to update"
        required: true
        type: choice
        options:
          - daemon
          - web
          - db
      revision:
        description: "Which revision to install"
        type: string
        required: true
        default: "latest"
      desired-count:
        description: "Desired count of services"
        type: string
        required: true
        default: "1"

jobs:
  update:
    if: github.repository != 'tmfg/digitraffic-road'
    runs-on: ubuntu-22.04
    environment: ${{ github.event.inputs.env }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Update
        uses: tmfg/digitraffic-actions@ecs-service-update/v1
        with:
          revision: ${{ github.event.inputs.revision }}
          service-name: road-${{ github.event.inputs.env }}-${{ github.event.inputs.family-name }}
          aws-role: ${{ secrets.AWS_ROLE }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}
          desired-count: ${{ github.event.inputs.desired-count }}
